### ISSUE TITLE
Fail when building variable font: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontmake#1066]
Hi!

I have this error when I'm trying to build these [fonts](https://github.com/emmamarichal/Gelasio/tree/main/test/sources):

`fontmake: Error: In 'master_ufo/Gelasio.designspace': Generating fonts from Designspace failed: maximum recursion depth exceeded while calling a Python object`

I read these issues: 
https://github.com/googlefonts/fontmake/issues/452 
https://github.com/googlefonts/glyphsLib/issues/375

And according to them, I cleaned the background and checked if there were not any images or components in it.
I also checked if there were any bracket layers, there are none.
I also converted .glyphspackage to .glyphs (we never know).

Any idea? cc @m4rc1e 

**To reproduce**
I used 
- gftools 0.9.43
- fontmake 3.7.1
https://github.com/emmamarichal/Gelasio/tree/main/test/sources

**Comment by anthrotype** [comment]
please try with --verbose DEBUG and copy paste the full traceback error

**Comment by emmamarichal** [comment]
[Gelasio_traceback-error.zip](https://github.com/googlefonts/fontmake/files/13965646/Gelasio_traceback-error.zip)

**Comment by anthrotype** [comment]
Thanks.. Strange, the ufo2ft.util.getMaxComponentDepth function is failing with recursion error. Will investigate.

```
Traceback (most recent call last):
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 517, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 263, in compileTTF
    glyphSet = call_preprocessor(ufo, **kwargs)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 76, in call_preprocessor
    return preProcessor.process()
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/preProcessor.py", line 101, in process
    func(ufo, glyphSet)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/filters/base.py", line 197, in __call__
    orderedGlyphs = sorted(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/filters/base.py", line 198, in <lambda>
    glyphSet.keys(), key=lambda g: -getMaxComponentDepth(glyphSet[g], glyphSet)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/util.py", line 621, in getMaxComponentDepth
    componentDepth = getMaxComponentDepth(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/util.py", line 621, in getMaxComponentDepth
    componentDepth = getMaxComponentDepth(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/util.py", line 621, in getMaxComponentDepth
    componentDepth = getMaxComponentDepth(
  [Previous line repeated 977 more times]
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/util.py", line 618, in getMaxComponentDepth
    baseGlyph = glyphSet[component.baseGlyph]
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/__main__.py", line 698, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 923, in run_from_glyphs
    self.run_from_designspace(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 1187, in run_from_designspace
    self._run_from_designspace_static(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 1277, in _run_from_designspace_static
    self.run_from_ufos(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 1365, in run_from_ufos
    self.build_ttfs(ufos, inplace=inplace, **kwargs)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 320, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 680, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 519, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'Gelasio.glyphs' -> 'master_ufo/Gelasio.designspace': Compiling UFO failed: maximum recursion depth exceeded while calling a Python object
```

**Comment by anthrotype** [comment]
there seems to be a circular reference among components in your font. Even Glyphs.app shows a "bad reference", take a look at the cedilla component in Ccedilla composite glyph

<img width="435" alt="Screenshot 2024-01-18 at 12 25 14" src="https://github.com/googlefonts/fontmake/assets/6939968/27011359-520e-4981-8833-31e7ee136224">

We could try improve the error message but we can't build a font like that.

**Comment by anthrotype** [comment]
yeah, so the glyph "cedilla" references the component "cedillacomb", and in turn the glyph "cedillacomb" references the "cedilla" as component. One or the other has to be a simple glyph, they can't be both component of one another ad infinitum

**Comment by anthrotype** [comment]
I'm a bit surprised a font editor would let one create things like this to begin with

**Comment by emmamarichal** [comment]
Oh I understand better now. I commented a fontbakery issue about it: https://github.com/fonttools/fontbakery/issues/4403#issuecomment-1888798454

But it's weird that I didn't see the issue, I'm pretty sure there was no problem when I looked at this, but the files haven't changed...so I guess I was tired haha

Thank you!!

**Comment by emmamarichal** [comment]
Ah, this is the file where the cedilla were still here: https://github.com/SorkinType/Gelasio/tree/main/sources/Gelasio.glyphspackage
(I knew I saw it somewhere)
