### ISSUE TITLE
fontmake shouldn't interpolate instances whose location matches masters

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/fontmake#336]
from the log building variable fonts from https://github.com/googlei18n/noto-source/tree/master/src/NotoNastaliqUrdu

_
============= src/NotoNastaliqUrdu/NotoNastaliqUrdu-MM.plist ==============
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Bold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.7.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 488, in run_from_ufos
    ufos, reverse_direction, conversion_error, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 204, in build_interpolatable_ttfs
    conversion_error=conversion_error)
  File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 159, in convert_curves
    reverse_direction=reverse_direction, dump_stats=True)
  File "/usr/local/lib/python2.7/dist-packages/cu2qu/ufo.py", line 260, in fonts_to_quadratic
    glyphs, cur_max_errors, reverse_direction, stats)
  File "/usr/local/lib/python2.7/dist-packages/cu2qu/ufo.py", line 165, in _glyphs_to_quadratic
    raise IncompatibleGlyphsError(*glyphs)
cu2qu.ufo.IncompatibleGlyphsError: 'Noon'_

**Comment by anthrotype** [comment]
source error, I'd say. The error is raised by cu2qu when converting masters "compatibly", when a glyph's contours are either different lengths (number of segments for each contour is different), or any of segments have different types (lines vs curve).

**Comment by punchcutter** [comment]
The Nastaliq Regular and Bold are not master compatible. They weren't intended to be. As far as I know this was the single exception in Noto due to the design and the fact that Nastaliq style doesn't lend itself very well to a bunch of different weights. Perhaps Regular and Bold shouldn't be in the same Glyphs file in this case, but it is kind of nice to have them in a single file. There could be a flag to say don't try interpolation, etc. for a situation like this.

**Comment by anthrotype** [comment]
I see.

I think for cases like these fontmake (or whomever down the pipeline is responsible for that, e.g. glyphsLib, mutatormath, etc.) should not try to interpolate instances whose location in the design space matches exactly one of the masters', but should simply use the master's outlines plus the rest of the instance data (e.g. the custom parameters) to build the final OTF.

Maybe mutatorMath should do that.

**Comment by anthrotype** [comment]
needless to say, if the masters are not compatible one cannot expect fontmake to produce a variable font. In the case of Noto Nastaliq Urdu the build script that calls fontmake should be changed so that it doesn't ask fontmake to also output a variable font, but only two non-variable Regular and Bold instances.

**Comment by madig** [comment]
Fontmake 2.0.0's new Instantiator will not run anything through varLib if an instance location matches a master location.
