### ISSUE TITLE
Building a static font from quadratic source: NotImplementedError in RemoveOverlapsFilter

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontmake#530]
I'm attempting to build a font with fontmake, but it's failing. This seems to be due to `qcurves` in the UFO source glyphs.

```
(venv) ▶ fontmake -o otf -u "Route Sans-Display Bold.ufo"
----------------------------------------------------------
INFO:fontmake.font_project:Building OTF for RouteSans-Bold
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on RouteSans-Bold
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on RouteSans-Bold
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/route-project/venv/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 410, in main
    ufo_paths, is_instance=args.pop("masters_as_instances"), **args
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 974, in run_from_ufos
    self.build_otfs(ufos, **kwargs)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 269, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 533, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 396, in _iter_compile
    yield compile_func(ufo, **options)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/ufo2ft/__init__.py", line 97, in compileOTF
    glyphSet = preProcessor.process()
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/ufo2ft/preProcessor.py", line 46, in process
    func(ufo, glyphSet)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/ufo2ft/filters/__init__.py", line 212, in __call__
    if include(glyph) and filter_(glyph):
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/ufo2ft/filters/removeOverlaps.py", line 58, in filter
    self.union(contours, pen)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 101, in union
    return _performOperation("union", contours, [], outPen)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 90, in _performOperation
    outputContour.reCurveSubSegments(inputContours)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/booleanOperations/flatten.py", line 807, in reCurveSubSegments
    tValues = inputSegment.tValueForPoint(searchPoint)
  File "/Users/stephennixon/type-repos/route-project/venv/lib/python3.7/site-packages/booleanOperations/flatten.py", line 255, in tValueForPoint
    raise NotImplementedError
NotImplementedError
```

It does working if I pass in the `--keep-overlaps` flag, but in a static, I don't want to keep overlaps.

When I look into line 255 of `flatten.py`, it seems that it is failing to remove overlap because it is considering the segment type to be `qcurve`.

```
elif self.segmentType == "qcurve":
            raise NotImplementedError
```

Is it not possible to remove overlap in statics when building from a quadratic source?

**Comment by anthrotype** [comment]
Can you try using the alternative remove-overlap backend, i.e. skia-pathops? There should be a flag to enable that with fontmake, check the —help
You’ll have to install fontmake as `pip install fontmake[pathops]`, as that is an optional extra requirement.

We should mention this in the readme. PR anyone?

**Comment by anthrotype** [comment]
Btw, yes booleanOperations does not support quadratic curves, there should be an open issue about that on its repo.

The link to the skia-pathops project is https://github.com/fonttools/skia-pathops

**Comment by thundernixon** [comment]
Thanks so much for this advice! It's a side project, but I'll try out your suggestion as soon as possible. 

If it works on my end, I'll make a quick PR on the readme to explain how it worked.

**Comment by anthrotype** [comment]
with latest booleanOperations at least it tells why why it fails and which glyphs has the unsupported segment type.

**Comment by sursly** [comment]
Hi @anthrotype, regarding your comment above, how would one go about using the alternative remove-overlap? I've installed skia-pathops but I'm not sure how/what to add to my fontmake build script. Any help would be great!

**Comment by madig** [comment]
Look for the `--overlaps-backend` in `fontmake --help`.

**Comment by sursly** [comment]
Yeah, found it, beautiful!, Thanks.
