### ISSUE TITLE
Can build VF only with --no-production-names

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/fontmake#556]
```
$ fontmake -o variable -g Test.glyphs 
```

fails with an error (assert {} in locations, "Base master not found.") in fontTools.varLib._addHVAR, which I couldn't figure out. Turns out it works if I specify `--no-production-names`. Any ideas why this happens?

OK:
```
$ fontmake -o variable --no-production-names -g Test.glyphs 
```

[Test.glyphs.zip](https://github.com/googlefonts/fontmake/files/3232806/Test.glyphs.zip)

The traceback:

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Test.glyphs" file into <GSFont>
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 2: 30, 3: 4
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on TheSansMono-CdM2
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on TheSansMono-CdM9
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on TheSansMono-M2
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on TheSansMono-M9
INFO:ufo2ft:Building OpenType tables for TheSansMono-CdM2
INFO:ufo2ft.postProcessor:Compiling TrueType hinting
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:ufo2ft:Building OpenType tables for TheSansMono-CdM9
INFO:ufo2ft.postProcessor:Compiling TrueType hinting
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:ufo2ft:Building OpenType tables for TheSansMono-M2
INFO:ufo2ft.postProcessor:Compiling TrueType hinting
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:ufo2ft:Building OpenType tables for TheSansMono-M9
INFO:ufo2ft.postProcessor:Compiling TrueType hinting
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:fontmake.font_project:Building variable font variable_ttf/TheSansMono-VF.ttf
INFO:fontTools.varLib:Axes:
[{'default': 200.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(200.0, 53.0), (900.0, 184.0)],
  'maximum': 900.0,
  'minimum': 200.0,
  'name': 'Weight',
  'tag': 'wght'},
 {'default': 80.0,
  'hidden': False,
  'labelNames': {'en': 'Width'},
  'map': [(80.0, 500.0), (100.0, 600.0)],
  'maximum': 100.0,
  'minimum': 80.0,
  'name': 'Width',
  'tag': 'wdth'}]
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 53.0, 'Width': 500.0},
 {'Weight': 184.0, 'Width': 500.0},
 {'Weight': 53.0, 'Width': 600.0},
 {'Weight': 184.0, 'Width': 600.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [53.0, 53.0, 184.0], 'Width': [500.0, 500.0, 600.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': 0.0, 'Width': 0.0},
 {'Weight': 1.0, 'Width': 0.0},
 {'Weight': 0.0, 'Width': 1.0},
 {'Weight': 1.0, 'Width': 1.0}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:No need for avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:Generating HVAR
Traceback (most recent call last):
  File "/Users/jens/Library/Python/3.7/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/__main__.py", line 380, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 718, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 864, in run_from_designspace
    **kwargs
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 920, in _run_from_designspace_interpolatable
    ttf_designspace, output_path=output_path, output_dir=output_dir
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 374, in build_variable_font
    font, _, _ = varLib.build(designspace, finder)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/__init__.py", line 912, in build
    _add_HVAR(vf, model, master_fonts, axisTags)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/__init__.py", line 476, in _add_HVAR
    _add_VHVAR(font, masterModel, master_ttfs, axisTags, hvarFields)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/__init__.py", line 507, in _add_VHVAR
    vOrigMetricses)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/__init__.py", line 529, in _get_advance_metrics
    vhAdvanceDeltasAndSupports[glyph] = masterModel.getDeltasAndSupports(vhAdvances)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/models.py", line 364, in getDeltasAndSupports
    model, items = self.getSubModel(items)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/models.py", line 219, in getSubModel
    subModel = VariationModel(subList(key, self.origLocations), self.axisOrder)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/models.py", line 203, in __init__
    keyFunc = self.getMasterLocationsSortKeyFunc(locations, axisOrder=self.axisOrder)
  File "/Users/jens/Code/fonttools/Lib/fontTools/varLib/models.py", line 225, in getMasterLocationsSortKeyFunc
    assert {} in locations, "Base master not found."
AssertionError: Base master not found.
```

**Comment by jenskutilek** [comment]
A glyph name related error also happens when I just try to build TTFs:

```
$ fontmake -o ttf -g Test.glyphs
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Test.glyphs" file into <GSFont>
INFO:fontmake.font_project:Building TTF for TheSansMono-CdM2
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on TheSansMono-CdM2
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on TheSansMono-CdM2
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on TheSansMono-CdM2
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 1, 2: 29, 3: 3
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Compiling TrueType hinting
INFO:ufo2ft.postProcessor:Renaming glyphs to final production names
INFO:fontmake.font_project:Saving master_ttf/TheSansMono-CdM2.ttf
Traceback (most recent call last):
  File "/Users/jens/Library/Python/3.7/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/__main__.py", line 380, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 718, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 857, in run_from_designspace
    **kwargs
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 909, in _run_from_designspace_static
    **kwargs
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 979, in run_from_ufos
    self.build_ttfs(ufos, **kwargs)
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 272, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/Users/jens/Code/fonttools/Lib/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/jens/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 562, in save_otfs
    font.save(otf_path)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/ttFont.py", line 629, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/tables/_m_a_x_p.py", line 45, in compile
    self.recalc(ttFont)
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/tables/_m_a_x_p.py", line 78, in recalc
    g = glyfTable[glyphName]
  File "/Users/jens/Code/fonttools/Lib/fontTools/ttLib/tables/_g_l_y_f.py", line 229, in __getitem__
    glyph = self.glyphs[glyphName]
KeyError: 'uni0308'
```

**Comment by jenskutilek** [comment]
Probably an error in my code. Sorry.
