### ISSUE TITLE
Are sparse masters supported?

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontmake#559]
Are sparse masters supported? I thought they were, but I can't get [Source Code Pro](https://github.com/adobe-fonts/source-code-pro/) to build as a variable TTF. The intermediate UFO master (Regular) does not contain the full glyph set.

**Comment by anthrotype** [comment]
They should, yes. What error do you get?
I can try to have a look later today or early next week

**Comment by miguelsousa** [comment]
Command and output below. The process balks when it's processing the sparse master.

    fontmake -m Roman/Masters/SourceCodeVariable-Roman.designspace -o variable --production-names --feature-writer None

```
INFO:fontmake.font_project:Building variable font variable_ttf/SourceCodeVariable-Roman-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 207, 2: 3218, 3: 1277, 4: 119, 5: 19, 6: 18, 7: 2
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceCode_ExtraLight
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceCodeVariable-Roman
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on SourceCode_Black
INFO:ufo2ft:Building OpenType tables for SourceCode_ExtraLight
INFO:ufo2ft:Building OpenType tables for SourceCodeVariable-Roman
Traceback (most recent call last):
  File "fontmake", line 11, in <module>
    sys.exit(main())
  File "fontmake/__main__.py", line 407, in main
    project.run_from_designspace(designspace_path, **args)
  File "fontmake/font_project.py", line 914, in run_from_designspace
    **kwargs
  File "fontmake/font_project.py", line 969, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "fontmake/font_project.py", line 411, in build_variable_font
    inplace=True,
  File "ufo2ft/__init__.py", line 542, in compileVariableTTF
    inplace=inplace,
  File "ufo2ft/__init__.py", line 388, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "ufo2ft/__init__.py", line 299, in compileInterpolatableTTFs
    featureCompilerClass=featureCompilerClass,
  File "ufo2ft/__init__.py", line 500, in compileFeatures
    return featureCompiler.compile()
  File "ufo2ft/featureCompiler.py", line 126, in compile
    self.buildTables()
  File "ufo2ft/featureCompiler.py", line 244, in buildTables
    addOpenTypeFeaturesFromString(self.ttFont, self.features, filename=path)
  File "fontTools/feaLib/builder.py", line 32, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile, tables=tables)
  File "fontTools/feaLib/builder.py", line 23, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "fontTools/feaLib/builder.py", line 133, in build
    table = self.makeTable(tag)
  File "fontTools/feaLib/builder.py", line 544, in makeTable
    table.LookupList.Lookup = self.buildLookups_(tag)
  File "fontTools/feaLib/builder.py", line 534, in buildLookups_
    return [l.build() for l in lookups]
  File "fontTools/feaLib/builder.py", line 534, in <listcomp>
    return [l.build() for l in lookups]
  File "fontTools/feaLib/builder.py", line 1649, in build
    subtables = otl.buildSinglePos(self.mapping, self.glyphMap)
  File "fontTools/otlLib/builder.py", line 434, in buildSinglePos
    st = buildSinglePosSubtable({g: values[key]}, glyphMap)
  File "fontTools/otlLib/builder.py", line 452, in buildSinglePosSubtable
    self.Coverage = buildCoverage(values.keys(), glyphMap)
  File "fontTools/otlLib/builder.py", line 11, in buildCoverage
    self.glyphs = sorted(glyphs, key=glyphMap.__getitem__)
KeyError: 'breveinverteddoublecmb'
```

**Comment by miguelsousa** [comment]
Think I found the problem. The sparse master had a `features.fea` file that referenced non-sparsed GSUB features.

**Comment by anthrotype** [comment]
glad that you solved it :)

**Comment by weiweihuanghuang** [comment]
I think I might be having this problem... is the correct protocol to not have any features.fea file in the sparse masters then?
