### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by alexmyczko** [googlefonts/fontmake#583]
Running `fontmake -i -o otf -g sources/glyphs/Gemunu-latin.glyphs` I get:

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "sources/glyphs/Gemunu-latin.glyphs" file into <GSFont>
Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==2.0.1', 'console_scripts', 'fontmake')()
  File "/usr/lib/python3/dist-packages/fontmake/__main__.py", line 405, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 647, in run_from_glyphs
    write_skipexportglyphs=write_skipexportglyphs,
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 374, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 151, in build_master_ufos
    write_skipexportglyphs=write_skipexportglyphs,
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/__init__.py", line 112, in to_designspace
    return builder.designspace
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/builders.py", line 259, in designspace
    self.to_designspace_axes()
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/axes.py", line 198, in to_designspace_axes
    regularUserLoc = interp(reverse_mapping, regularDesignLoc)
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/axes.py", line 580, in interp
    return ya + float(x - xa) / (xb - xa) * (yb - ya)
ZeroDivisionError: float division by zero
```

Find the glyphs file at `https://github.com/mooniak/gemunu-libre-font/blob/master/sources/glyphs/Gemunu-latin.glyphs`

**Comment by anthrotype** [comment]
Try assigning all your instances the same width class from the instance tab's `Width` drop-down men  (e.g. "Medium (normal)").
Your masters only vary along weight, there is no reason for the instances to have differing width class.

I understand that error message could be improved, or better avoided altogether.
I'll open a separate issue in glyphsLib.
