### ISSUE TITLE
KeyError: 'Ezh' may I get more information about this error code ?

### ISSUE THREAD

**Issue by thierryc** [googlefonts/fontmake#584]
Help!

When I try to build a font from a UFO src doc, I get this error. 
May I get more information about this error?

```
Python 3.7
```

Error log
```
fontmake -u dist/MyFontName/DesignSpace-UFO/masters/MyFontName-Regular.ufo -o ttf --output-dir fonts/
INFO:fontmake.font_project:Building TTF for MyFontName-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on MyFontName-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on MyFontName-Regular
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on MyFontName-Regular
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 66, 2: 866, 3: 701, 4: 184, 5: 14, 6: 1
INFO:ufo2ft:Building OpenType tables
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 440, in main
    ufo_paths, is_instance=args.pop("masters_as_instances"), **args
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 996, in run_from_ufos
    self.build_ttfs(ufos, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 201, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 374, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 462, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 329, in _iter_compile
    yield compile_func(ufo, **options)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 210, in compileTTF
    featureCompilerClass=featureCompilerClass,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 500, in compileFeatures
    return featureCompiler.compile()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 120, in compile
    self.setupFeatures()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 218, in setupFeatures
    writer.write(self.ufo, featureFile, compiler=self)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureWriters/baseFeatureWriter.py", line 113, in write
    return self._write()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureWriters/markFeatureWriter.py", line 690, in _write
    features = self._makeFeatures()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureWriters/markFeatureWriter.py", line 639, in _makeFeatures
    indicGlyphs = self._getIndicGlyphs()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureWriters/markFeatureWriter.py", line 676, in _getIndicGlyphs
    gsub = self.compileGSUB()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureWriters/baseFeatureWriter.py", line 176, in compileGSUB
    gsub = compileGSUB(self.context.feaFile, glyphOrder)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/util.py", line 213, in compileGSUB
    addOpenTypeFeatures(font, featureFile, tables={"GSUB"})
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 21, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 131, in build
    table = self.makeTable(tag)
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 542, in makeTable
    table.LookupList.Lookup = self.buildLookups_(tag)
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 532, in buildLookups_
    return [l.build() for l in lookups]
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 532, in <listcomp>
    return [l.build() for l in lookups]
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 1275, in build
    self.setBacktrackCoverage_(prefix, st)
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 1156, in setBacktrackCoverage_
    coverage = otl.buildCoverage(p, self.glyphMap)
  File "/Users/thierry/Library/Python/3.7/lib/python/site-packages/fontTools/otlLib/builder.py", line 11, in buildCoverage
    self.glyphs = sorted(glyphs, key=glyphMap.__getitem__)
KeyError: 'Ezh'
```

**Comment by madig** [comment]
When you see "KeyError" and "feaLib" somewhere near the bottom of the stack trace somewhere, the most likely explanation is that you reference "Ezh" in the feature file somewhere when the glyph does not exist in the UFO.

**Comment by thierryc** [comment]
Thank you for your help.

**Comment by madig** [comment]
Did that fix the issue?

**Comment by thierryc** [comment]
Yes definitively, thank you again for your smart and quick response @madig.

Thierry

**Comment by anthrotype** [comment]
We should have feaLib raise a specific exception when features reference missing glyphs so ufo2ft and this fontmake can catch that and provide a more human-friendly error message
