### ISSUE TITLE
Log the culprit glyph name in remove overlap

### ISSUE THREAD

**Issue by typoman** [googlefonts/fontmake#596]
I remember a simialr issue somewhere but I can't find it! Is there any way to get which glyph is causing an error in removeOverlaps filter. It would be nifty if ufo2ft logged the glyph name. Log:

```
ERROR:ufo2ft.filters.removeOverlaps:Failed to remove overlaps for mim.fina.stencil
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 440, in main
    ufo_paths, is_instance=args.pop("masters_as_instances"), **args
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 995, in run_from_ufos
    self.build_otfs(ufos, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 197, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Users/bahmaneslami/Github/fonttools/Lib/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 462, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 329, in _iter_compile
    yield compile_func(ufo, **options)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 111, in compileOTF
    glyphSet = preProcessor.process()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/preProcessor.py", line 49, in process
    func(ufo, glyphSet)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/filters/__init__.py", line 219, in __call__
    if include(glyph) and filter_(glyph):
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/filters/removeOverlaps.py", line 50, in filter
    self.union(contours, pen)
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 101, in union
    return _performOperation("union", contours, [], outPen)
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 70, in _performOperation
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/booleanOperationManager.py", line 70, in <listcomp>
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/flatten.py", line 65, in __init__
    contour.drawPoints(pointPen)
  File "/usr/local/lib/python3.7/site-packages/defcon/objects/contour.py", line 664, in drawPoints
    pointPen.addPoint((point.x, point.y), segmentType=point.segmentType, smooth=point.smooth, name=point.name, identifier=point.identifier)
  File "/usr/local/lib/python3.7/site-packages/booleanOperations/flatten.py", line 344, in addPoint
    raise OpenContourError("Unhandled open contour")
booleanOperations.exceptions.OpenContourError: Unhandled open contour
```

**Comment by typoman** [comment]
Sorry found the name in the log! ( ͡° ͜ʖ ͡°)

**Comment by madig** [comment]
I think burying the error message with the culprit with a stack trace is suboptimal. Hm. It's almost as if fontmake should never output a stack trace without `--log-level debug` and by default log an error message with the exception.

**Comment by typoman** [comment]
I was looking at the bottom to find the glyph name somewhere in the traceback, that's why I didn't find it in the beginning.

**Comment by madig** [comment]
Yeah. The stack trace hides the more important error message.

**Comment by anthrotype** [comment]
> fontmake should never output a stack trace without --log-level debug and by default log an error message with the exception.

sounds good. At least for more common errors that have clear and specific cause such as this one.
