### ISSUE TITLE
Sparse / Partial Masters and Anchors

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontmake#607]
I'm having some issues with this VF project where I have some sparse masters, I get the following error:
```
INFO:fontTools.varLib:Merging OpenType Layout tables
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontmake/__main__.py", line 407, in main
    project.run_from_designspace(designspace_path, **args)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 914, in run_from_designspace
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 969, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 411, in build_variable_font
    inplace=True,
  File "/usr/local/lib/python2.7/site-packages/ufo2ft/__init__.py", line 577, in compileVariableTTF
    ttfDesignSpace, exclude=excludeVariationTables, optimize=optimizeGvar
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 916, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 688, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 111, in mergeTables
    for m in master_ttfs])
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 1003, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 76, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 1003, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 76, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 1003, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 76, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 1003, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 99, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 82, in mergeLists
    assert allEqualTo(out, lst, len), (len(out), [len(v) for v in lst])
AssertionError: ((3, [3, 3, 3, 3, 1, 1, 2, 2]), 'list', '.Coverage', 'MarkGlyphSetsDef', '.MarkGlyphSetsDef', 'GDEF', '.table', 'table_G_D_E_F_')
```
I understand issue is to do with the anchors, and the issue doesn't present when I don't have the sparse masters. 

Is there something I need to do especially with the anchors when I have sparse masters?

**Comment by madig** [comment]
By sparse UFO master you mean an actual UFO with less glyphs than the others? Or do you mean Glyphs-style brace layers?

**Comment by anthrotype** [comment]
If you could share (publicly or privately) the sources it could help with debugging.
Please if you can try not to use python 2.7 as it's no longer supported.

**Comment by arrowtype** [comment]
As far as I understand it (though I could definitely be incorrect / behind), "sparse masters" in the typical sense are not currently supported by the UFO/designspace/FontMake workflow.

You _can_, however, point to "support" layers as sources. Mutator Sans does this:

```XML
    <source filename="MutatorSansLightCondensed.ufo" familyname="MutatorMathTest" stylename="LightCondensed" layer="support.crossbar">
      <location>
        <dimension name="width" xvalue="0"/>
        <dimension name="weight" xvalue="700"/>
      </location>
    </source>
    <source filename="MutatorSansLightCondensed.ufo" familyname="MutatorMathTest" stylename="LightCondensed" layer="support.S.wide">
      <location>
        <dimension name="width" xvalue="1000"/>
        <dimension name="weight" xvalue="700"/>
      </location>
    </source>
    <source filename="MutatorSansLightCondensed.ufo" familyname="MutatorMathTest" stylename="LightCondensed" layer="support.S.middle">
      <location>
        <dimension name="width" xvalue="569.078000"/>
        <dimension name="weight" xvalue="700"/>
      </location>
    </source>
```

https://github.com/LettError/mutatorSans/blob/5c179fe3ba1cb39b7922389eb942e7beb9614742/MutatorSans.designspace#L51-L68 

I've tried this workflow and got it working well enough, but found that it was a fairly big additional obstacle in getting consistency-checking tools and scripts to work (from Prepolator to my own little drawing-QA scripts). Maybe, however, you could solve this by using of a sparse-master approach, but having a build step that turns things into support layers.

Of course, it would be really nice if FontMake did eventually support sparse masters!

**Comment by anthrotype** [comment]
Well, support layers _are_ sparse masters.
What exactly do you mean by that?

**Comment by anthrotype** [comment]
Ok I see the problem. Ufo2ft assumes that when a source is a whole UFO then it can have features of its own and makes kern and mark features for it (depending on the presence of kerning and anchors), which end up in a GPOS and GDEF table; whereas it doesn't do that for sources that are specified as support layers within a UFO.
There is a mechanism for disabling the generation of automatic kern/mark features for a specific UFO, by setting some lib key in the lib plist. Maybe that could be used to prevent ufo2ft from generating incompatible GPOS or GDEF tables when a UFO is meant to be treated as a sparse master.

**Comment by anthrotype** [comment]
What is most typical workflow when designing fonts with sparse masters, to make separate master fonts or separate support layers? I was under the impression that the latter would be more common in the UFO world, as the example of MutatorSans above suggests.

**Comment by arrowtype** [comment]
> What is most typical workflow when designing fonts with sparse masters

I can't answer this in a general sense, but in my experience, tools tend to work best when glyphs are all on the same layer, in separate masters. 

As a simple example: it's easy to write a Python script for RoboFont to loop through AllFonts(), and check for similarity between points, anchors, unicodes, etc. It adds significant complexity to have to also check support layers in such a script.

![image](https://user-images.githubusercontent.com/45946693/69916556-fa0f3b80-1421-11ea-9a9e-0cda2ca9b139.png)

**Comment by anthrotype** [comment]
there's another difference between DS sources specified as whole UFOs vs support layers. For the latter, we only compile tables relating to glyph outlines and glyph metrics, see:

https://github.com/googlefonts/ufo2ft/blob/33954355c9c00c59e3b20645444f865ccd77e907/Lib/ufo2ft/constants.py#L3-L6

whereas the whole UFO sort of sources are treated as being "non-sparse" and as such we build also vertical font metrics tables and font-wide metadata and names.

So if one want to use a distinct UFO source as a sparse master (instead of a support layer), one would then also have to duplicate all these font-wide info from the neutral master if they do not want them to participate in, e.g. defining the MVAR table. Leaving these info blank would most likely end up generating different hhea and OS/2 tables for the sparse masters.

**Comment by justvanrossum** [comment]
>  Ufo2ft assumes that when a source is a whole UFO then it can have features of its own and makes kern and mark features for it (depending on the presence of kerning and anchors), which end up in a GPOS and GDEF table; whereas it doesn't do that for sources that are specified as support layers within a UFO.

I ran into this a while ago but didn't have the opportunity to dig in deeper and report. I think this is a misguided assumption. If I want to use a specific (non-default) layer as a master, I expect this to work identically as when I would want the default layer. Vice versa, I'd expect a "whole ufo" (default layer) to work as a sparse master.

**Comment by justvanrossum** [comment]
Perhaps it needs to be specified explicitly whether a master is sparse or not.

**Comment by madig** [comment]
Source Sans Pro/Variable uses standalone UFOs as sparse masters last time I checked.

**Comment by weiweihuanghuang** [comment]
After having worked on both .glyphs with brace layer and UFO with entire masters for interpolation correction, I personally prefer working with entire masters actually – it feels much more robust to be able to see the whole master.

**Comment by weiweihuanghuang** [comment]
So in the meantime to get my setup working, I need to copy all those sparse masters to one of the main UFOs as a support layer?

**Comment by justvanrossum** [comment]
> Or, what does Source Sans Pro do to make it work?

Wild guess: perhaps it doesn't use mark/base anchors on glyphs that may be sparse.

**Comment by weiweihuanghuang** [comment]
I wonder if it will work if I keep the have the full character set in there, but leave the unused glyphs empty and set a mute in the .designspace for those glyphs.

**Comment by justvanrossum** [comment]
I don't think varLib supports glyph muting.

I wouldn't mind having a look if you can share your UFOs + .designspace files (that cause the initial error) with me privately. (my gh user name @ gmail.com)

**Comment by anthrotype** [comment]
@weiweihuanghuang Try to add a "com.github.googlei18n.ufo2ft.featureWriters" dict to the sparse UFO's `lib.plist` containing an empty array of feature writers. This will override the ufo2ft's default list of writers (i.e. KernFeatureWriter and MarkFeatureWriter) for that specific UFO. An empty array means "do not generate any automatic features". Since the sparse UFO will not contain any features.fea of its own, the generated master TTFs will also not contain any OTL tables.

To add that lib key from python you can do:

```python
import defcon

font = defcon.Font("YourSparseMaster.ufo")
font.lib["com.github.googlei18n.ufo2ft.featureWriters"] = []
font.save()
```

The lib.plist would look like this:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.github.googlei18n.ufo2ft.featureWriters</key>
    <array/>
  </dict>
</plist>
```

Let me know if that works for you, thanks

**Comment by madig** [comment]
I remember that we explicitly turn off feature generation for sparse layers in ufo2ft precisely due to the sparseness.

**Comment by anthrotype** [comment]
>  we explicitly turn off feature generation for sparse layers in ufo2ft precisely due to the sparseness.

of course, sparse _layers_ can't have their own features.fea. The problem here is that, when one attempts to use a distinct UFO as a _sparse_ master (i.e. its main layer contains only some but not all the glyphs of the neutral master), ufo2ft will assume that the UFO source is _not_ sparse and hence it will try to build kern and mark/mkmk features, possibly leading to incompatible GPOS/GDEF tables that varLib fails to merge.

**Comment by anthrotype** [comment]
> Perhaps it needs to be specified explicitly whether a master is sparse or not.

yes, maybe the DesignSpace source element can have some attribute that make that more explicit. Let's think about that.

**Comment by madig** [comment]
Which implies that much like sparse layers, sparse masters can not change any features in any way, i.e. you can't move anchor positions, only ever outlines and spacing.

**Comment by justvanrossum** [comment]
> Which implies that much like sparse layers, sparse masters can not change any features in any way, i.e. you can't move anchor positions, only ever outlines and spacing. Hm. Kerning?

Right. I can see sparse kerning (to touch up specific pairs at a specific location) as a potentially useful thing. I'm not sure if the use case is very strong, though. (A master could for example _only_ contain kerning, and not a single glyph.)

Anchor positions is perhaps the bigger issue here. If you want an intermediate glyph outline, you'd want any anchors to also interpolate with it.

Tangential aside: I've worked on a project where we'd have intermediate masters for spacing but _not_ outlines. I achieved it with a gvar post processing script. The use case was possibly a little obscure: it was to achieve perfect metrics compatibility with legacy fonts at specific locations, while still saving space by not having outlines there.

**Comment by madig** [comment]
> The use case was possibly a little obscure: it was to achieve perfect metrics compatibility with legacy fonts at specific locations, while still saving space by not having outlines there.

But useful, because this might apply to any larger project that needs to be made variable :) Good idea.

**Comment by weiweihuanghuang** [comment]
> Since the sparse UFO will not contain any features.fea of its own, the generated master TTFs will also not contain any OTL tables.
So does this mean no opentype features at all in generated TTFs (specifically those generated at the location where the sparse masters are, or just any TTF including the VF-TTF)?

>Anchor positions is perhaps the bigger issue here. If you want an intermediate glyph outline, you'd want any anchors to also interpolate with it.

In the current project, I have glyphs in the sparse master where I am only moving the anchor...

**Comment by weiweihuanghuang** [comment]
@anthrotype I tried your suggestion and the family generates now!
I have recreated the structure of the project with my own Work Sans here to reproduce the same issues: [WS.zip](https://github.com/googlefonts/fontmake/files/3913747/WS.zip)

`WorkSans-Sparse.designspace` recreates the above 
issue.
`WorkSans-Sparse-EmptyFeatureWriters.designspace` uses the sparse UFO with the empty feature writer.

**Comment by arrowtype** [comment]
Awesome; can’t wait to try this workflow!

**Comment by madig** [comment]
> I tried to move a anchor in a glyph in the sparse master with the empty feature writer, and that wasn't reflected in the end vf-ttf

Probably. Anchors exist only in the GPOS table, which is written by feature writers. Currently, you can only use sparse masters and layers to change outlines and spacing and nothing else.

Not sure what is needed to make this work more broadly...

**Comment by twardoch** [comment]
One thing I'll add: FontLab 7 lers you do sparse masters but the way we
build VF is that we feed a designspace and or own TTFs into varLib. One
thing we had to change was to build GSUB only for the main master,
otherwise varLib was trying to varmerge incompatible GSUBs and failed.

For GPOS, somehow it works with kern, because of the way we build the kern
feature I guess, but other GPOS feature varmerging is still a big issue.

I personally think that work would need to be done on GPOS varmerging in
varLib so it's not "stupid". I think right now it just goes by lookup
indices and GIDs. But it probably should go by single rules, adding deltas
to actual rules defined in lookups assigned to specific features.

Alternatively, there could be a GPOS feature compiler/writer that takes a
neutral GPOS, and your static sparse, and then builds a fake master that is
based on the neutral, but with the sparse glyphs patched in, and with a
GPOS where all the adjustments are set to 0 except those defined in the
sparse GPOS.

And then varLib would use that. Well, actually, this is the way that
FontLab could build the pseudo-sparse TTFs that go into varLib merging :)
Hell. :D

**Comment by twardoch** [comment]
One thing I'll add: FontLab 7 lers you do sparse masters but the way we build VF is that we feed a designspace and or own TTFs into varLib. One thing we had to change was to build GSUB only for the main master, otherwise varLib was trying to varmerge incompatible GSUBs and failed.

For GPOS, somehow it works with kern, because of the way we build the kern feature I guess, but other GPOS feature varmerging is still a big issue.

I personally think that work would need to be done on GPOS varmerging in varLib so it's not "stupid". I think right now it just goes by lookup indices and GIDs. But it probably should go by single rules, adding deltas to actual rules defined in lookups assigned to specific features. 

Alternatively, there could be a GPOS feature compiler/writer that takes a neutral GPOS, and your static sparse, and then builds a fake master that is based on the neutral, but with the sparse glyphs patched in, and with a GPOS where all the adjustments are set to 0 except those defined in the sparse GPOS. 

And then varLib would use that. Well, actually, this is the way that FontLab could build the pseudo-sparse TTFs that go into varLib merging :) Hell. :D

**Comment by twardoch** [comment]
BTW, this could be part of a VF "completer" that we've talked about. Another functionality of the completer could be filling in missing masters. You know that the Designspace for VF needs all masters to be addressable from the neutral by a single move along one axis, and also how .designspace does not allow you to define regions for intermediates.

So right now, what one needs to do is to turn a dev designspace into a production designspace by:

1. Adding missing masters. For example when I have 2 axes with 4 corner masters and I'd like to use the center as my neutral — 5 more masters are then needed to go from 4 to 9. These masters CAN be interpolated from the 4, and THEN varLib could build the VF. That could be a step done by the completer.

2. Adding countermasters for intermediates. If you have 2 axes with 4 corner masters and you add 1 intermediate at one of the edges, due to the way VF works, it's unrestricted so it pushes all it's deltas to the opposite edge, ruining the interpolation. So a countermaster is needed at the opposite end, which is purely interpolated without taking that intermediate into account. Than you have 6 masters, not 5, and then you get the result you want. Again, this can also be done in software, so it's a task for the completer.

And the other completer task could be "desparsing" sparse masters that I talked about above. 

It's not a hard problem. Figuring out the locations for the locations of the extra masters needs to be done carefully. But overall, it's solvable but code needs to be written. 

It's also a "universal" solution — by large, I think there's only one good way to solve this. So that qualifies for an opensource tool, unfortunately one that is beyond my abilities.

**Comment by weiweihuanghuang** [comment]
Just noticed using the [above project sampl](https://github.com/googlefonts/fontmake/files/3913747/WS.zip) I shared to generate an instance, I get some 16,000 kerning pairs, whereas generating the same instance without the intermediate masters in the above project, I get around 2900... I wonder if that has to do with this issue https://github.com/googlefonts/fontmake/issues/625

**Comment by weiweihuanghuang** [comment]
Actually I looked into it more, it seems regardless of whether the sparse intermediate master is part of the designspace or not, the generated instance UFO has 2300 pairs, but the generated TTF has 16000 pairs (strangely when the sparse intermediate master _is_ in there's 19,000 pairs, which seems odd given that there isn't even kerning in the sparse intermediate master)

**Comment by madig** [comment]
How do you measure the number of kern pairs? Do you see a pattern which glyphs get new kern pairs? Are these along the interpolation axes?

**Comment by weiweihuanghuang** [comment]
Brace layers seemed to stop working somewhere in the last versions? 
https://github.com/googlefonts/fontmake/issues/399

**Comment by kontur** [comment]
I _think_ I've run into this as well when compiling a variable font from UFOs extracted from Glyphsapp that have brace layers.

The file is a basic 2 master `wght` setup but some glyphs have swashes where the extent of the swash is exposed in the VF as `swsh` axis and defined solely on as brace layers for those few glyphs where swashes are applicable. In the designspace there are two weight masters, as well as the two brace layer masters for the swash axis extrema. Those compiled fonts don't interpolate the mark positions on the `swsh` axis / brace layers. 

My _crude_ solution was to make the brace layers explicit standalone UFOs (copy weight master UFOs, copy brace layer glyphs to regular glyphs, remove layers, reference standalones in designspace).

**Comment by anthrotype** [comment]
it would help if you could provide a reproducer. I also suggest trying with older versions of glyphsLib in case this is some sort of regression (pip install glyphsLib=={version}, see https://github.com/googlefonts/glyphsLib/releases)

**Comment by kontur** [comment]
[mark-debug-test-case.zip](https://github.com/googlefonts/fontmake/files/14082999/mark-debug-test-case.zip)

This includes a glyph source and faulty VF as described above. The VF is compiled in two steps, first use fontmake to extract, then I modified the designspace (the designspace doesn't get extended to the swsh max if those are only encountered in brace layers, but nvm that), then compile VF with fontmake. The files, a test string and requirements.txt are inside the archive with full information.

**Comment by anthrotype** [comment]
> (the designspace doesn't get extended to the swsh max if those are only encountered in brace layers, but nvm that)

maybe "Axis Mappings" custom parameter would fix that

**Comment by anthrotype** [comment]
btw, thanks for the file I'll take a look soon

**Comment by anthrotype** [comment]
> some glyphs have swashes where the extent of the swash is exposed in the VF as swsh axis and defined solely as brace layers for those few glyphs where swashes are applicable

**Comment by anthrotype** [comment]
> some glyphs have swashes where the extent of the swash is exposed in the VF as swsh axis and defined solely as brace layers for those few glyphs where swashes are applicable

isn't that the use case for so-called Virtual Masters? I think we now support those

**Comment by anthrotype** [comment]
see https://github.com/googlefonts/glyphsLib/pull/955

**Comment by kontur** [comment]
> maybe "Axis Mappings" custom parameter would fix that

Ah yea, could be. In this case the designspace file is tweaked in other regards as well with `<rules>` and modifying the instance list from the default glyphsLib spits out, so not an issue.

> isn't that the use case for so-called Virtual Masters? I think we now support those

Need to check that, first I've seen about it 👍
