### ISSUE TITLE
Kerning creating AssertionError in VF build

### ISSUE THREAD

**Issue by sponcey** [googlefonts/fontmake#617]
I'm trying to build a VF. I am able to create a successful build when I remove kerning info, but when I add kerning info to one master, it throws the following AssertionError. All masters have matching kerning groups, but not matching kerning pairs.

[.designspace file trying to build from here](https://github.com/undercasetype/Fraunces/blob/master/sources/current_masters/Roman/fraunces-varfontprep-2019_12_12-16_46_02/Fraunces_GoofyAxis.designspace)

What does this error mean? 

> Traceback (most recent call last):
  File "/Users/Cadmon/env/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontmake/__main__.py", line 444, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontmake/font_project.py", line 896, in run_from_designspace
    **kwargs,
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontmake/font_project.py", line 962, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontmake/font_project.py", line 310, in build_variable_font
    inplace=True,
  File "/Users/Cadmon/env/lib/python3.7/site-packages/ufo2ft/__init__.py", line 577, in compileVariableTTF
    ttfDesignSpace, exclude=excludeVariationTables, optimize=optimizeGvar
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 874, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 595, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 109, in mergeTables
    for m in master_ttfs])
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 97, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 83, in mergeLists
    self.mergeThings(value, values)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 823, in merge
    merger.mergeObjects(self, lst, exclude=['SubTable', 'SubTableCount'])
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/Cadmon/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 99, in mergeThings
    assert allEqualTo(out, lst), (out, lst)
AssertionError: ((8, [0, 8, 0, 8, 8, 8, 8, 8]), 'int', '.LookupFlag', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by madig** [comment]
You have a `kern` feature in two feature.fea files. Fontmake by default skips kerning.plist if it finds a pre-existing `kern` feature.

**Comment by sponcey** [comment]
Ah, that was the problem! I added a kern feature to all masters and was able to successfully build. Thank you!
