### ISSUE TITLE
fontmake.instantiator.InstantiatorError: Can't generate UFOs from this designspace: no default font.

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#628]
I have a [Glyphs source](https://github.com/yanone/Sen/blob/master/Glyphs/sen.glyphs) here that should easily compile into fonts with `fontmake` as far as I'm concerned.

It's the most simple setup: Two master, three instances. Yet, when I build using `fontmake -g ./Glyphs/sen.glyphs -o ttf -i --output-dir $TTFDIR` (taken from build script), the following traceback appears:

```
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 672, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 889, in run_from_designspace
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 932, in _run_from_designspace_static
    expand_features_to_instances=expand_features_to_instances,
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 707, in interpolate_instance_ufos
    designspace, round_geometry=round_instances
  File "/usr/local/lib/python3.7/site-packages/fontmake/instantiator.py", line 185, in from_designspace
    "Can't generate UFOs from this designspace: no default font."
fontmake.instantiator.InstantiatorError: Can't generate UFOs from this designspace: no default font.
```

What am I doing wrong?

**Comment by arrowtype** [comment]
Do you have a instanced at the same locations as your default master? E.g. if the font is light-bold, do you have an instance at light?

**Comment by yanone** [comment]
There is a Regular master as well as instance. But this was never necessary. Mind you, this is not a VF.

**Comment by arrowtype** [comment]
Oh, you are just going to UFOs. Hmm, not sure what might be blocking this. Maybe just using GlyphsLib alone would be more successful?

**Comment by yanone** [comment]
> Oh, you are just going to UFOs. Hmm, not sure what might be blocking this. Maybe just using GlyphsLib alone would be more successful?

Doesn't sound familiar. I just want to build TTFs from a Glyphs source in the most top-level way like so: `fontmake -g ./Glyphs/sen.glyphs -o ttf -i --output-dir $TTFDIR` (obviously $TTFDIR holding a value in the build script)
This has always worked.

**Comment by madig** [comment]
> WARNING:glyphsLib.builder.axes:Instance user-space location (100) redefined by 'ExtraBold'

All instances must have unique (Weight, Width, Custom) values or you get this warning and a messed up axis mapping. Since the default font is determined from the axis default values, you get an error about a missing default master.

**Comment by yanone** [comment]
This error doesn't make sense to me. All instances have unique axis coordinates: 400, 650, 900. The masters are at 400 and 900.
And again: This is not a VF. It used to work.

**Comment by madig** [comment]
Add a font-level custom parameter "Axes" and declare a single "Weight" axis.

![image](https://user-images.githubusercontent.com/380829/72535819-1996e200-3871-11ea-85af-9872eea3e81a.png)

The axis mapping code in glyphsLib is murky.

**Comment by yanone** [comment]
That worked. Thank you so much.

**Comment by davelab6** [comment]
On chat @yanone said,

> This was never necessary in Glyphs. All masters and instances had only weight axes values, so the existence of a weight axis, if even necessary in Glyphs at all, can be inferred from the data. 

So, can fontmake infer it correctly and "just work"?

**Comment by madig** [comment]
I think we tried to make it "just work" several times over the centuries. Glyphs is a moving target.
