### ISSUE TITLE
AssertionError.

### ISSUE THREAD

**Issue by sevenc-nanashi** [googlefonts/fontmake#687]
```
PS E:\workspace\Python> fontmake -u ufo2.ufo  -o otf --verbose DEBUG
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building OTF for MinecraftUnicode-None
INFO:ufo2ft:Pre-processing glyphs
DEBUG:ufo2ft.filters.removeOverlaps:using booleanOperations as RemoveOverlapsFilter backend
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on MinecraftUnicode-Regular
INFO:ufo2ft.filters:Running RemoveOverlapsFilter on MinecraftUnicode-Regular
DEBUG:ufo2ft.filters:Took 3.316s to run RemoveOverlapsFilter on 1415 glyphs
INFO:ufo2ft:Building OpenType tables
DEBUG:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
DEBUG:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
DEBUG:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
DEBUG:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
DEBUG:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
DEBUG:ufo2ft.featureWriters.kernFeatureWriter.KernFeatureWriter:No kerning data; skipped
DEBUG:ufo2ft.featureWriters.markFeatureWriter.MarkFeatureWriter:No mark-attaching anchors found; skipped
DEBUG:fontTools.ttLib.ttFont:compiling 'maxp' table
DEBUG:fontTools.ttLib.ttFont:writing 'maxp' table to disk
DEBUG:fontTools.ttLib.ttFont:compiling 'CFF ' table
ERROR:root:In 'minecraft_ufo2.ufo': Compiling UFO failed
Traceback (most recent call last):
  File "c:\develop\python\lib\site-packages\fontmake\font_project.py", line 365, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "c:\develop\python\lib\site-packages\ufo2ft\__init__.py", line 150, in compileOTF
    postProcessor = PostProcessor(otf, ufo, glyphSet=glyphSet)
  File "c:\develop\python\lib\site-packages\ufo2ft\postProcessor.py", line 46, in __init__
    otf.save(stream)
  File "c:\develop\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "c:\develop\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\develop\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 628, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "c:\develop\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\develop\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "c:\develop\python\lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 19, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "c:\develop\python\lib\site-packages\fontTools\cffLib\__init__.py", line 192, in compile
    writer.toFile(file)
  File "c:\develop\python\lib\site-packages\fontTools\cffLib\__init__.py", line 418, in toFile
    assert posList == lastPosList
AssertionError



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\develop\python\lib\site-packages\fontmake\__main__.py", line 471, in main
    project.run_from_ufos(
  File "c:\develop\python\lib\site-packages\fontmake\font_project.py", line 1055, in run_from_ufos
    self.build_otfs(ufos, cff_version=cff_version, **kwargs)
  File "c:\develop\python\lib\site-packages\fontmake\font_project.py", line 218, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "c:\develop\python\lib\site-packages\fontTools\misc\loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "c:\develop\python\lib\site-packages\fontmake\font_project.py", line 490, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "c:\develop\python\lib\site-packages\fontmake\font_project.py", line 367, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'minecraft_ufo2.ufo': Compiling UFO failed
```
Is this a fontmake glitch? or Base file glitch?

**Comment by sevenc-nanashi** [comment]
[ufo2.zip](https://github.com/googlefonts/fontmake/files/5009917/ufo2.zip)

**Comment by punchcutter** [comment]
Your glyphOrder has a lot of non ASCII characters in it instead of glyph names. Deleting the glyphOrder or regenerating it with glyph names makes it work. How did this glyphOrder get generated?

**Comment by sevenc-nanashi** [comment]
With Python.(defcon)

**Comment by sevenc-nanashi** [comment]
```
import os
#import xml.etree.ElementTree as ET
#import shutil
Base="test"
ld2=os.listdir(path=f'./{Base}/glyphs')
r=""
with open(f'{Base}/glyphs/contents.plist',"r",encoding="utf-8") as f:
	r=f.read()
with open(f'{Base}/glyphs/contents.plist',"w",encoding="utf-8") as f:
	for l in ld2:
		if l == "contents.plist":
			continue
		r=r.replace(f"<string>{l}</string>",f"<string>{str(ord(l[0]))}.glif</string>")
		
		os.rename(f'{Base}/glyphs/{l}',f'{Base}/glyphs/{ord(l[0])}.glif')
	print(r)
	f.write(r)
```
I used this script, and it works now!
Thank you.
(I hope this script helps someone :) )

**Comment by sevenc-nanashi** [comment]
Wait,it didn't work :(
