### ISSUE TITLE
Fontmake and TrueType hinting / Glyphs sources

### ISSUE THREAD

**Issue by monokromskriftforlag** [googlefonts/fontmake#705]
Trying to build the designspace from hinted (TrueType) Glyphs sources, I run into the following: 

> fontmake: Error: In 'myfont.glyphs': Loading Glyphs file failed: 'NoneType' object has no attribute 'groups'

The exact same file stripped of hints and hinting-related tables exports without problems.

**Comment by davelab6** [comment]
This is for a Google Fonts release

**Comment by anthrotype** [comment]
please re-run fontmake with `--verbose DEBUG` option and copy-paste the full exception traceback.
It might be a bug in glyphsLib

**Comment by monokromskriftforlag** [comment]
Generating Designspace and UFOs
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
ERROR:root:In 'myfont_hinted.glyphs': Loading Glyphs file failed: [Errno 2] No such file or directory: 'myfont_hinted.glyphs'
Traceback (most recent call last):
  File "/Users/frodehelland/Documents/MyFont/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 154, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/Users/frodehelland/Documents/MyFont/venv/lib/python3.8/site-packages/glyphsLib/classes.py", line 3650, in __init__
    with open(path, "r", encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'myfont_hinted.glyphs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/frodehelland/Documents/MyFont/venv/lib/python3.8/site-packages/fontmake/__main__.py", line 437, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/frodehelland/Documents/MyFont/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 668, in run_from_glyphs
    designspace_path = self.build_master_ufos(
  File "/Users/frodehelland/Documents/MyFont/venv/lib/python3.8/site-packages/fontTools/misc/loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "/Users/frodehelland/Documents/MyFont/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 156, in build_master_ufos
    raise FontmakeError("Loading Glyphs file failed", glyphs_path) from e
fontmake.errors.FontmakeError: In 'myfont_hinted.glyphs': Loading Glyphs file failed: [Errno 2] No such file or directory: 'myfont_hinted.glyphs'

**Comment by m4rc1e** [comment]
Your input file, "myfont_hinted.glyphs" doesn't exist. Perhaps the file exists but the path to it isn't correct?

In your first post the file was also called "myfont.glyphs"

**Comment by monokromskriftforlag** [comment]
Sorry, I was running it again and the path was indeed wrong (plus a little search/replace of the names in the code). Here is the error I get with a correct path.

Generating Designspace and UFOs
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "myfont-hinted.glyphs" file into <GSFont>
ERROR:root:In 'myfont-hinted.glyphs': Loading Glyphs file failed: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 154, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/classes.py", line 3653, in __init__
    p.parse_into_object(self, fp.read())
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 63, in parse_into_object
    i = self._parse_dict_into_object(res, text, 1)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/parser.py", line 125, in _parse
    value = self.current_type(value)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/classes.py", line 255, in parse_hint_target
    return Point(line)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/types.py", line 129, in __init__
    self.value = self.fromString(value)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/glyphsLib/types.py", line 96, in fromString
    return [parse_float_or_int(i) for i in self.regex.match(src).groups()]
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/fontmake/__main__.py", line 437, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 668, in run_from_glyphs
    designspace_path = self.build_master_ufos(
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/fontTools/misc/loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "/Users/frodehelland/Documents/Myfont/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 156, in build_master_ufos
    raise FontmakeError("Loading Glyphs file failed", glyphs_path) from e
fontmake.errors.FontmakeError: In 'myfont-hinted.glyphs': Loading Glyphs file failed: 'NoneType' object has no attribute 'groups'

**Comment by simoncozens** [comment]
glyphsLib doesn't support Glyphs 3 yet.

**Comment by monokromskriftforlag** [comment]
Hi @simoncozens. I’m not running Glyphs 3.

**Comment by simoncozens** [comment]
Oh. So maybe glyphsLib was *never* able to parse hints correctly. Oops.

**Comment by simoncozens** [comment]
OK, this is strange. I've had that exact error trying to parse Glyphs 3 files with hints, and it goes away without the hints, so that's what I assumed was behind it. Glyphs 2 hints look like this, and seem to parse fine:

```
hints = (
{
horizontal = 1;
origin = "{0, 11}";
target = "{0, 5}";
type = TTStem;
options = 4;
}
);
```

Glyphs 3 hints produce the "'NoneType' object has no attribute 'groups'" error and look like this:

```
hints = (
{
origin = (0,0);
target = (0,7);
}
```

Could you open your `.glyphs` file in an editor, find a "hints" section like those above, and paste a few lines (from one `{` to its corresponding `}` ) here?
