### ISSUE TITLE
TTF interpolation defects

### ISSUE THREAD

**Issue by dy** [googlefonts/fontmake#738]
Hello!
I am building a variable font for rendering waveforms, https://audio-lab.github.io/wavefont/, and observing an issue with interpolating TTF state.
Font has alignment axis, and instances define top-align and bottom-align masters, with values `algn` _1_ and _0_ respectively, see [descignspace file](https://github.com/audio-lab/wavefont/blob/master/masters/wavefont.designspace#L11). Center align state is expected to be interpolated by font.
And it is interpolated nicely by OTF font, generated with afdk:
![image](https://user-images.githubusercontent.com/300067/108613107-c91b7d80-73bc-11eb-9843-4eaf3956dbed.png)

But with TTF font, generated by fontmake, interpolation shows artifacts:
![image](https://user-images.githubusercontent.com/300067/108613105-bb65f800-73bc-11eb-8804-c23d9ce2c1ac.png)

What can that be related to?

**Comment by anthrotype** [comment]
you said you generated the OTF using afdko. What specific tool and exact command-line did you use to build it?

**Comment by dy** [comment]
buildmasterotfs -d masters/wavefont.designspace

and then

**Comment by anthrotype** [comment]
i'm unable to build your designspace using the command `fontmake -m masters/wavefont.designspace -o variable`, I'm getting this error (full traceback when running fontmake with `--verbose DEBUG`):

```
ERROR:root:In 'wavefont.designspace': Generating fonts from Designspace failed: The file '0.glif' associated with glyph '_0' in contents.plist does not exist on <osfs '/Users/clupo/Github/wavefont/masters/1_0.ufo'>/glyphs
Traceback (most recent call last):
  File "/Users/clupo/.local/pipx/venvs/fontmake/lib/python3.9/site-packages/fs/osfs.py", line 639, in open
    return io.open(
FileNotFoundError: [Errno 2] No such file or directory: b'/Users/clupo/Github/wavefont/masters/1_0.ufo/glyphs/0.glif'

[... omit for brevity ...]

fontTools.ufoLib.errors.GlifLibError: The file '0.glif' associated with glyph '_0' in contents.plist does not exist on <osfs '/Users/clupo/Github/wavefont/masters/1_0.ufo'>/glyphs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/clupo/.local/pipx/venvs/fontmake/lib/python3.9/site-packages/fontmake/__main__.py", line 464, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/clupo/.local/pipx/venvs/fontmake/lib/python3.9/site-packages/fontmake/font_project.py", line 947, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'wavefont.designspace': Generating fonts from Designspace failed: The file '0.glif' associated with glyph '_0' in contents.plist does not exist on <osfs '/Users/clupo/Github/wavefont/masters/1_0.ufo'>/glyphs
```

**Comment by dy** [comment]
Ah, sorry about that, yes, ‘npm run build’ should come first

**Comment by anthrotype** [comment]
still getting an error after running `npm run build` from the root of the wavefont repository directory.

```
$ npm run build

> wavefont@2.0.0 build
> npm run build-values-1-0 && npm run build-values-1-1 && npm run build-values-1-center && npm run build-values-100-0 && npm run build-values-100-1 && npm run build-ttf


> wavefont@2.0.0 build-values-1-0
> build-values.sh 1 0

sh: build-values.sh: command not found
npm ERR! code 127
npm ERR! path /Users/clupo/Github/wavefont
npm ERR! command failed
npm ERR! command sh -c build-values.sh 1 0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clupo/.npm/_logs/2021-02-22T11_45_38_224Z-debug.log
npm ERR! code 127
npm ERR! path /Users/clupo/Github/wavefont
npm ERR! command failed
npm ERR! command sh -c npm run build-values-1-0 && npm run build-values-1-1 && npm run build-values-1-center && npm run build-values-100-0 && npm run build-values-100-1 && npm run build-ttf

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clupo/.npm/_logs/2021-02-22T11_45_38_250Z-debug.log
```

**Comment by dy** [comment]
Hm, try maybe `sudo chmod +x build-values.sh` `sudo chmod +x build-values-center.sh`. Are you running in macOS?

**Comment by anthrotype** [comment]
even after setting the executable flag I get the same error when doing npm run build. I was able to run the shell scripts one by one. Yes, i'm running macos 10.15, with node installed via homebrew. I have no idea why it fails like that, I'm no js expert.

Ok, I built the variable font with fontmake 2.3.0, this is what I got:

[Uploading wavefont-VF.ttf.zip…]()

but it's now obvious to me how I can reproduce those glitches you reported in the screenshot.

Where did you render the font? What OS or browser or app? What text string and variation settings?

**Comment by dy** [comment]
Observing the same issue with your font.
Brave/windows:
![image](https://user-images.githubusercontent.com/300067/108753234-794eca80-7512-11eb-9671-700c61798118.png)
Firefox/windows:
![image](https://user-images.githubusercontent.com/300067/108753326-997e8980-7512-11eb-8760-dfc4da1c48b9.png)

Works fine in Safari macOS and iPhone.
That can possibly be platform problem, unless there are interpolation settings inside the font itself.

**Comment by dy** [comment]
It has something to do with order of points in contour.
Swapping contour to 
```diff
    <contour>
+     <point x="0" y="0" type="line"/>
      <point x="0" y="10" type="line"/>
      <point x="100" y="10" type="line"/>
      <point x="100" y="0" type="line"/>
-     <point x="0" y="0" type="line"/>
    </contour>
```
moves that saw to the bottom:
![image](https://user-images.githubusercontent.com/300067/108755382-2e828200-7515-11eb-8c87-8bdf74d91e56.png)

**Comment by anthrotype** [comment]
the fact it only happens on some browsers and not all of them, and the fact that it only happens for TTFs, makes me think this might have to do with so-called "inferred variation deltas" which are only found in TrueType-flavoured variable OpenType fonts: https://docs.microsoft.com/en-us/typography/opentype/spec/gvar#inferred-deltas-for-un-referenced-point-numbers

Could you please try to rebuild the VF using the option `--no-optimize-gvar` and see if that changes the result?

**Comment by dy** [comment]
> this might have to do with so-called "inferred variation deltas"
> rebuild the VF using the option --no-optimize-gvar

Brilliant. It worked! Many thanks.
Should that issue be addressed here or can be closed?

**Comment by anthrotype** [comment]
hm, that's not good. It means there are bugs in the way the font's gvar is interpreted in some environments. It'd be better to file issues with the affected browsers.
Could you provide an easy way to reproduce this, like a zip file containing the two fonts with and without inferred gvar deltas, and an html file using both with some strings and feature settings so one can load that in various browsers?

**Comment by anthrotype** [comment]
also note that disabling the gvar optimization makes the VF slightly bigger (by how much it depends).

**Comment by dy** [comment]
For this particular case there's no size difference.
Attached the minimal demo:
[ttf-gvar-issue.zip](https://github.com/googlefonts/fontmake/files/6024763/ttf-gvar-issue.zip)

**Comment by anthrotype** [comment]
thanks! I think the the `src: url(...)` point to the same wavefont.ttf, but the files are named wavefont-good.ttf and wavefont-bad.ttf. 
Otherwise, works, thanks

Just tried on my macOS Chrome and could not reproduce.

**Comment by dy** [comment]
Whoops. This one is corrected.
[ttf-gvar.zip](https://github.com/googlefonts/fontmake/files/6024865/ttf-gvar.zip)
