### ISSUE TITLE
Error generating NotoSerifDevanagari

### ISSUE THREAD

**Issue by JelleBosmaMT** [googlefonts/fontmake#745]
Trying to generate fonts from Noto Serif Devanagari I get this error:

`fontmake: Error: In 'NotoSerifDevanagari-MM.glyphs' -> 'master_ufo/NotoSerifDevanagari.designspace' -> 'master_ufo/NotoSerifDevanagari-Light.ufo': Compiling UFO failed: <features>:6089:9: Expected '{'`

Version fontmake 2.3.1 with Python 3.8 on Mac.
Used command: python3 fontmake -g "NotoSerifDevanagari-MM.glyphs"

The error message was not very meaningful to me. If there is is a missing { in the embedded feature code, I do not think Glyphs.app would manage to generate fonts. That made me suspect the GPOS code. I could generate fonts after removing all the anchors. I haven't tried to narrow it down any further.

Attached a ZIP file with the latest Monotype version of the Glyphs file.

[NotoSerifDevanagari-MM.glyphs.zip](https://github.com/googlefonts/fontmake/files/6068300/NotoSerifDevanagari-MM.glyphs.zip)

**Comment by anthrotype** [comment]
please retry with the option `--verbose DEBUG` that shows the full exception traceback and paste it here, thanks.

(we should really tackle #652 since a lot of user are left with meaningless error messages and don't know that running fontmake --verbose DEBUG would show them the traceback)

**Comment by JelleBosmaMT** [comment]
```
ERROR:ufo2ft.featureCompiler:Compilation failed! Inspect temporary file: '/var/folders/ts/myyzy69n00vbgqhn0w_v_pfw0000gn/T/tmpgbqxkzzm'
ERROR:root:In 'NotoSerifDevanagari-MM.glyphs' -> 'master_ufo/NotoSerifDevanagari.designspace' -> 'master_ufo/NotoSerifDevanagari-Light.ufo': Compiling UFO failed: <features>:6089:9: Expected '{'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 376, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ufo2ft/__init__.py", line 138, in compileOTF
    compileFeatures(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ufo2ft/__init__.py", line 556, in compileFeatures
    otFont = featureCompiler.compile()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ufo2ft/featureCompiler.py", line 130, in compile
    self.buildTables()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ufo2ft/featureCompiler.py", line 252, in buildTables
    addOpenTypeFeaturesFromString(self.ttFont, self.features, filename=path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/builder.py", line 84, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile, tables=tables, debug=debug)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/builder.py", line 59, in addOpenTypeFeatures
    builder.build(tables=tables, debug=debug)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/builder.py", line 165, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/parser.py", line 103, in parse
    statements.append(self.parse_feature_block_())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/parser.py", line 1437, in parse_feature_block_
    self.parse_block_(block, vertical, stylisticset, size_feature, cv_feature)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/parser.py", line 1611, in parse_block_
    statements.append(self.parse_lookup_(vertical))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/parser.py", line 588, in parse_lookup_
    self.parse_block_(block, vertical)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/parser.py", line 1587, in parse_block_
    self.expect_symbol_("{")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/feaLib/parser.py", line 1800, in expect_symbol_
    raise FeatureLibError("Expected '%s'" % symbol, self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: <features>:6089:9: Expected '{'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/__main__.py", line 451, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 696, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 926, in run_from_designspace
    self._run_from_designspace_static(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 1002, in _run_from_designspace_static
    self.run_from_ufos(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 1073, in run_from_ufos
    self.build_otfs(ufos, cff_version=cff_version, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 222, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/misc/loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 506, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 378, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'NotoSerifDevanagari-MM.glyphs' -> 'master_ufo/NotoSerifDevanagari.designspace' -> 'master_ufo/NotoSerifDevanagari-Light.ufo': Compiling UFO failed: <features>:6089:9: Expected '{'

```

**Comment by punchcutter** [comment]
`lookup abvm_mark2mark_#topRight` doesn't look good. There are anchors named `#topRight` so that's probably being treated as a comment in the fea parsing.

**Comment by punchcutter** [comment]
I renamed `#topRight` to get rid of the `#` and then it doesn't fail.

**Comment by JelleBosmaMT** [comment]
It helps that Zachary is the one person that combines knowledge of fontmake _and_ Noto Serif Devanagari.

**Comment by JelleBosmaMT** [comment]
According the the Glyphs documentation _If you want to avoid automatic generation of such GPOS feature code, and use the corresponding anchors solely for compound alignment, you can prefix the anchor names with an arbitrary non-letter, e.g., #top and _#top, as well as #exit and #entry._
In other words changing the name of these anchors will prevent fontmaker to fail, but adds unintended mark attachment entries to the GPOS. The #topright anchors should be ignored for feature code.

**Comment by JelleBosmaMT** [comment]
I removed the #topright anchors, which may not be needed after completion of the design anyway.

Now it is possible to generate TTFs. I do get a lot of warnings along the line of `INFO:ufo2ft.featureWriters.markFeatureWriter.MarkFeatureWriter:The base glyph marwaridd_ya-deva and mark glyph nukta_rrVocalicMatra-deva are ambiguously connected by several anchor classes: MC_nukta, MC_bottom. The last one will prevail.`
I guess I should make a comparison with the Glyphs generated TTFs to see if this goes well or not.

However, if I try to generate a variable font, I get a new error. I still have a variable font generated in January with all anchors removed, so the problem is probably still anchor related.

I used this command: `python3 fontmake -g "NotoSerifDevanagari-MM.glyphs" -o variable --verbose DEBUG`

With this file
[NotoSerifDevanagari-MM.glyphs 2.zip](https://github.com/googlefonts/fontmake/files/6083665/NotoSerifDevanagari-MM.glyphs.2.zip)

And ended with this message:

```
ERROR:root:In 'NotoSerifDevanagari-MM.glyphs' -> 'master_ufo/NotoSerifDevanagari.designspace': Generating fonts from Designspace failed: ((11, [11, 11, 11, 11, 11, 14, 11, 11]), 'list', '.glyphs', 'Coverage', '[0]', 'list', '.Coverage', 'MarkGlyphSetsDef', '.MarkGlyphSetsDef', 'GDEF', '.table', 'table_G_D_E_F_')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 939, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 1018, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 326, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ufo2ft/__init__.py", line 615, in compileVariableTTF
    varfont = varLib.build(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/__init__.py", line 926, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/__init__.py", line 619, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 118, in mergeTables
    self.mergeThings(font[tag], [m[tag] if tag in m else None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 1043, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 104, in mergeThings
    self.mergeObjects(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 81, in mergeObjects
    mergerFunc(self, value, values)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 1043, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 104, in mergeThings
    self.mergeObjects(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 81, in mergeObjects
    mergerFunc(self, value, values)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 1043, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 104, in mergeThings
    self.mergeObjects(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 81, in mergeObjects
    mergerFunc(self, value, values)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 1043, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 106, in mergeThings
    self.mergeLists(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 91, in mergeLists
    self.mergeThings(value, values)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 1043, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 104, in mergeThings
    self.mergeObjects(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 81, in mergeObjects
    mergerFunc(self, value, values)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 1043, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 106, in mergeThings
    self.mergeLists(out, lst)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontTools/varLib/merger.py", line 88, in mergeLists
    raise VarLibMergeError((len(out), [len(v) for v in lst]))
fontTools.varLib.errors.VarLibMergeError: ((11, [11, 11, 11, 11, 11, 14, 11, 11]), 'list', '.glyphs', 'Coverage', '[0]', 'list', '.Coverage', 'MarkGlyphSetsDef', '.MarkGlyphSetsDef', 'GDEF', '.table', 'table_G_D_E_F_')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/__main__.py", line 451, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 696, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fontmake/font_project.py", line 952, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'NotoSerifDevanagari-MM.glyphs' -> 'master_ufo/NotoSerifDevanagari.designspace': Generating fonts from Designspace failed: ((11, [11, 11, 11, 11, 11, 14, 11, 11]), 'list', '.glyphs', 'Coverage', '[0]', 'list', '.Coverage', 'MarkGlyphSetsDef', '.MarkGlyphSetsDef', 'GDEF', '.table', 'table_G_D_E_F_')
```

**Comment by punchcutter** [comment]
If you print out what's actually happening it shows that all masters are expecting 
`['eCandraMatra-deva', 'oeMatra-deva', 'eLongCandra-deva', 'candraBindu-deva', 'invertedCandrabindu-deva', 'eCandraMatra_anusvara-deva', 'eCandraMatra_candrabindu-deva', 'oeMatra_candrabindu-deva', 'oeMatra_anusvara-deva', 'ayMatra-deva', 'ayMatra_candraBindu-deva']`
but Condensed also has `'oeMatra_reph-deva', 'oeMatra_rephanusvara-deva', 'oeMatra_rephcandrabindu-deva'` which is why it says 11 and 14. Everything gets only those 11 glyphs, but for some reason these extra 3 are getting into the Condensed set. Not sure why without digging more into the code.
