### ISSUE TITLE
issue when using FontProject.build_variable_font()

### ISSUE THREAD

**Issue by RafalBuchner** [googlefonts/fontmake#849]
In my variable font building scripts I used to use designspace path as an argument for FontProject.build_variable_font().
It's been working until fontmake upgrade to v.3.1. 

```Python
import fontmake.font_project

font_project = fontmake.font_project.FontProject(verbose="WARNING", validate_ufo=True)
designspace_path = "space.designspace"
font_project.build_variable_font( designspace_path, output_path="test.ttf", )
```
Now I'm getting this attribute error:
```
Traceback (most recent call last):
  File "/Users/rafalbuchner/Desktop/TestFontMakeIssue/build_var_with_designspace_path.py", line 8, in <module>
    font_project.build_variable_font( designspace_path, output_path="test.ttf", )
  File "/Users/rafalbuchner/venvs/fontenv/lib/python3.9/site-packages/fontmake/font_project.py", line 338, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/Users/rafalbuchner/venvs/fontenv/lib/python3.9/site-packages/ufo2ft/__init__.py", line 535, in compileVariableTTF
    baseUfo = getDefaultMasterFont(designSpaceDoc)
  File "/Users/rafalbuchner/venvs/fontenv/lib/python3.9/site-packages/ufo2ft/util.py", line 426, in getDefaultMasterFont
    defaultSource = designSpaceDoc.findDefault()
AttributeError: 'str' object has no attribute 'findDefault'
```

I realised that maybe I should've pass DesignSpaceDocument object instead of string/path.
I did so:

```Python
from fontTools.designspaceLib import DesignSpaceDocument
import fontmake.font_project

font_project = fontmake.font_project.FontProject(verbose="WARNING", validate_ufo=True)

designspace_path = "space.designspace"

designspace = DesignSpaceDocument()
designspace.read(designspace_path)


font_project.build_variable_font( designspace, output_path="test.ttf", )
```

And now I'm getting this output.

```
Traceback (most recent call last):
  File "/Users/rafalbuchner/Desktop/TestFontMakeIssue/build_var_with_designspace_object.py", line 12, in <module>
    font_project.build_variable_font( designspace, output_path="test.ttf", )
  File "/Users/rafalbuchner/venvs/fontenv/lib/python3.9/site-packages/fontmake/font_project.py", line 338, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/Users/rafalbuchner/venvs/fontenv/lib/python3.9/site-packages/ufo2ft/__init__.py", line 535, in compileVariableTTF
    baseUfo = getDefaultMasterFont(designSpaceDoc)
  File "/Users/rafalbuchner/venvs/fontenv/lib/python3.9/site-packages/ufo2ft/util.py", line 436, in getDefaultMasterFont
    raise InvalidDesignSpaceData(
ufo2ft.errors.InvalidDesignSpaceData: DesignSpace source 'temp_master.0' is missing required 'font' attribute
```

Am I doing something wrong? or is it bug on fontmake or ufo2ft side?

Best, 
R

**Comment by RafalBuchner** [comment]
here is code example together with simple designspace and master files
[TestFontMakeIssue.zip](https://github.com/googlefonts/fontmake/files/7941894/TestFontMakeIssue.zip)

**Comment by anthrotype** [comment]
I'd recommend that, if you want to call fontmake from a python script, you run it as a subprocess, e.g. `subprocess.run(["fontmake", ...], check=True)` etc. rather than importing the FontProject class. Fontmake is primarily a console script, rather than a library with a stable API. The command line interface, on the other hand, is relatively stable.
If you still want to import it, you should expect things to break like these when we refactor internal code.
In this case, the build_variable_font method is expecting a DesignSpaceDocument with pre-loaded source fonts. So you have to call `loadSourceFonts` method with your font opener of choice (ufoLib2.Font.open or defcon.Font class), like fontmake does in https://github.com/googlefonts/fontmake/blob/main/Lib/fontmake/font_project.py#L252

**Comment by RafalBuchner** [comment]
Yeah, In the setup that I'm using, I prefer not to use subprocess.
Anyways, thank you @anthrotype! seems like `loadSourceFonts` works just fine!
