### ISSUE TITLE
Gftools builder: AttributeError: 'FoundANone' object has no attribute 'argv'

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontmake#858]
I'm trying to export a font which is quite simple (one weight axes, a regular and an italic), and I still have this error when I use gftools builder. You can find the files here: [[https://github.com/emmamarichal/Familjen-Grotesk]](https://github.com/emmamarichal/Familjen-Grotesk)
Last commit: [24fd988](https://github.com/emmamarichal/Familjen-Grotesk/commit/24fd98845b6d4720d7ec240bddbd5d54cf72381b)

Thanks :)
cc @RosaWagner

### Error report
I run `gftools builder config.yaml`

INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building variable font ../fonts/variable/FamiljenGrotesk-VF.ttf
Traceback (most recent call last):
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 968, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 1048, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 339, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 554, in compileVariableTTF
    varfont = varLib.build(
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/__init__.py", line 926, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/__init__.py", line 619, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 139, in mergeTables
    self.mergeThings(font[tag], [m[tag] if tag in m else None
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 127, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 102, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 127, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 102, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 127, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 102, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 129, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 112, in mergeLists
    self.mergeThings(value, values)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 125, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 833, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 112, in mergeLists
    self.mergeThings(value, values)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 125, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 267, in merge
    merger.mergeThings(self.Value, [v.Value for v in lst])
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1038, in mergeThings
    raise FoundANone(self, got=lst)
fontTools.varLib.errors.FoundANone: <exception str() failed>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 289, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 329, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 719, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 982, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marichalemma/Google/env/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 186, in build
    self.build_variable()
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 294, in build_variable
    self.logger.error("Could not build variable font: %s" % e)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontmake/errors.py", line 33, in __str__
    cause = str(self.__cause__) if self.__cause__ is not None else None
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/errors.py", line 61, in __str__
    offender_index, offender = self.offender
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/fontTools/varLib/errors.py", line 105, in offender
    cause = self.argv[0]
AttributeError: 'FoundANone' object has no attribute 'argv'

**Comment by RosaWagner** [comment]
btw this error occurs the same with building directly with Fontmake (only for variable format), using version of the last main branch. We also tried with removing all special layers etc.

**Comment by RosaWagner** [comment]
The fonts build when removing this kern feature

<img width="843" alt="Capture d’écran 2022-02-24 à 10 46 11" src="https://user-images.githubusercontent.com/12222436/155499846-37db5589-9a67-46dd-a777-768a94f4277f.png">

**Comment by anthrotype** [comment]
there are two problems here. One is a bug in fonttools (which should be reported on its issue tracker) whereby varLib's error logging mechanism fails with an unhandled AttributeError exception while trying to show a nicer error message to the user.
The other problem in the font sources which triggers varLib to (fail to) display an error message will be clearer once the first bug is fixed.

**Comment by anthrotype** [comment]
there was a typo in varLib.errors module, I fixed that on fonttools main branch. Could you try installing fonttools from github and see if you get a better error message now? Try cloning the https://github.com/fonttools/fonttools repo, then `cd` into it (`git pull` if you had already cloned it in the past, to update to latest HEAD) and then install with `pip install -e .`.
Or install directly from github with something like

```
pip install -e git+https://github.com/fonttools/fonttools.git#fonttools
```

**Comment by emmamarichal** [comment]
I installed it, I have this message now: 
index = [x is None for x in cause["got"]].index(True)
TypeError: 'VariationMerger' object is not subscriptable

**Comment by anthrotype** [comment]
wow, so broken 😅  /cc @simoncozens who added that feature

**Comment by anthrotype** [comment]
@emmamarichal I pushed another fix, please try again after doing `git pull` (if you installed from a cloned fonttools repo) or reinstall from github

**Comment by emmamarichal** [comment]
The export of statics works, but variable fonts don't. I have this message:

INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building variable font ../fonts/variable/FamiljenGrotesk-VF.ttf
ERROR:GFBuilder:Could not build variable font: In 'FamiljenGrotesk.glyphs' -> 'master_ufo/FamiljenGrotesk.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because one of the values in a list was empty when
it shouldn't have been. This happened while performing the following
operation: GPOS.table.LookupList.Lookup[1][1]

The problem is likely to be in Familjen Grotesk Regular:
[1]==[None, None]

INFO:GFBuilder:Creating variable fonts from FamiljenGrotesk-Italic.glyphs
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building variable font ../fonts/variable/FamiljenGrotesk-Italic-VF.ttf
ERROR:GFBuilder:Could not build variable font: In 'FamiljenGrotesk-Italic.glyphs' -> 'master_ufo/FamiljenGrotesk-Italic.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because one of the values in a list was empty when
it shouldn't have been. This happened while performing the following
operation: GPOS.table.LookupList.Lookup[1][1]

The problem is likely to be in Familjen Grotesk Italic:
[1]==[None, None]

**Comment by simoncozens** [comment]
That suggests there is something different in the positioning layout rules between the two masters. I tried replicating it, but it builds fine for me with the latest master of https://github.com/Familjen-Sthlm/Familjen-Grotesk.

**Comment by anthrotype** [comment]
because they disabled the manual kern feature with this commit https://github.com/Familjen-Sthlm/Familjen-Grotesk/commit/0399c721c994393fb6aac4646ce9cd26bdba07dc

try checking out just before that

**Comment by simoncozens** [comment]
Great - now I can reproduce, but I have no idea what this error means... :-)
