### ISSUE TITLE
Parsing vmtx failed with variable type error

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontmake#914]
When running fontmake on UFO generated by FontCreator 14, the following error was thrown (with `--verbose DEBUG`):
```
ERROR:root:In 'test.ufo': Compiling UFO failed: can only concatenate str (not "float") to str
Traceback (most recent call last):
  File "C:\py\Python310\lib\site\fontmake\font_project.py", line 394, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "C:\py\Python310\lib\site\ufo2ft\__init__.py", line 236, in compileTTF
    otf = call_outline_compiler(ufo, glyphSet, **kwargs)
  File "C:\py\Python310\lib\site\ufo2ft\__init__.py", line 69, in call_outline_compiler
    return outlineCompiler.compile()
  File "C:\py\Python310\lib\site\ufo2ft\outlineCompiler.py", line 152, in compile
    self.setupTable_vmtx()
  File "C:\py\Python310\lib\site\ufo2ft\outlineCompiler.py", line 866, in setupTable_vmtx
    verticalOrigin = _getVerticalOrigin(self.otf, glyph)
  File "C:\py\Python310\lib\site\ufo2ft\outlineCompiler.py", line 71, in _getVerticalOrigin
    return otRound(verticalOrigin)
  File "C:\py\Python310\lib\site\fontTools\misc\roundTools.py", line 42, in otRound
    return int(math.floor(value + 0.5))
TypeError: can only concatenate str (not "float") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\py\Python310\lib\site\fontmake\__main__.py", line 618, in main
    project.run_from_ufos(
  File "C:\py\Python310\lib\site\fontmake\font_project.py", line 1147, in run_from_ufos
    self.build_ttfs(ufos, **kwargs)
  File "C:\py\Python310\lib\site\fontmake\font_project.py", line 241, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "C:\py\Python310\lib\site\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "C:\py\Python310\lib\site\fontmake\font_project.py", line 535, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "C:\py\Python310\lib\site\fontmake\font_project.py", line 396, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'test.ufo': Compiling UFO failed: can only concatenate str (not "float") to str
```
The issues stem from the generated glyph vertical metrics in `glif`:
```xml
<?xml version='1.0' encoding='utf-8'?>
<glyph name="A" format="2">
  <advance width="943" height="1000" />
  <unicode hex="0041" />
  <anchor x="472" y="0" name="bottom" />
  <anchor x="849" y="0" name="ogonek" />
  <anchor x="462" y="726" name="top" />
  <outline>
    <contour>
      <point x="692" y="143" type="line" />
      <point x="692" y="299" type="line" />
      <point x="203" y="299" type="line" />
      <point x="203" y="143" type="line" />
    </contour>
    <contour>
      <point x="251" y="0" type="line" />
      <point x="320" y="199" />
      <point x="401" y="416" />
      <point x="479" y="623" type="curve" />
      <point x="442" y="623" type="line" />
      <point x="521" y="416" />
      <point x="602" y="197" />
      <point x="671" y="0" type="curve" />
      <point x="930" y="0" type="line" />
      <point x="648" y="726" type="line" />
      <point x="280" y="726" type="line" />
      <point x="0" y="0" type="line" />
    </contour>
  </outline>
  <lib>
    <dict>
      <key>public.verticalOrigin</key>
      <string>880</string>
    </dict>
  </lib>
</glyph>
```

Notice that `public.verticalOrigin` has a type of `string` instead of `integer`, which caused the value to be treated incorrectly. Maybe a check and warning will be suitable here?

(Also might need someone to inform the FontCreator team for below:
> public.verticalOrigin[(source)](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#publicverticalorigin)
This key is used for representing the “vertical origin” ‘y’ coordinate used for vertical layout. The value for the key **must be an integer or float**. This data is optional. Authoring tools can use this data and the advance element’s height attribute to create the VORG and vmtx tables.

)

**Comment by anthrotype** [comment]
If I understand this correctly, FontCreator is outputting a UFO with a public.verticalOrigin that is formatted as a `<string>` instead of a integer or float, is that right? In that case, the spec is clear and I would say this UFO has invalid data and I'm not sure there's anything to do on our end, besides alerting the FontCreator devs.

**Comment by NightFurySL2001** [comment]
Actually, yeah... that will be an error on FontCreator. It would be better if the error can be more specific, like warning that the type is incorrect? Otherwise this is a non-issue.
