### ISSUE TITLE
"Compiling UFO failed: <fontTools.feaLib.ast.GlyphName object at 0x10ea35b10>" with FontTools==4.35.0

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontmake#925]
I’m trying to build static OTFs from a Glyphs source, and getting the error traceback when I use `--verbose DEBUG`: 

```
ERROR:root:In 'sources/shantellsans-wght_ital_IRGL.glyphs' -> 'master_ufo/ShantellSans.designspace' -> 'master_ufo/shantell--light.ufo': Compiling UFO failed: <fontTools.feaLib.ast.GlyphName object at 0x10ea35b10>
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 439, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/__init__.py", line 193, in compileOTF
    compileFeatures(ufo, otf, glyphSet=glyphSet, **kwargs)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/__init__.py", line 507, in compileFeatures
    otFont = featureCompiler.compile()
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/featureCompiler.py", line 127, in compile
    self.setupFeatures()
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/featureCompiler.py", line 265, in setupFeatures
    writer.write(self.ufo, featureFile, compiler=self)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/featureWriters/baseFeatureWriter.py", line 131, in write
    return self._write()
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/featureWriters/cursFeatureWriter.py", line 119, in _write
    feature = self._makeCursiveFeature()
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/featureWriters/cursFeatureWriter.py", line 26, in _makeCursiveFeature
    gsub = self.compileGSUB()
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/featureWriters/baseFeatureWriter.py", line 321, in compileGSUB
    gsub = compileGSUB(self.context.feaFile, glyphOrder)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/ufo2ft/util.py", line 230, in compileGSUB
    addOpenTypeFeatures(font, featureFile, tables={"GSUB"})
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/feaLib/builder.py", line 64, in addOpenTypeFeatures
    builder.build(tables=tables, debug=debug)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/feaLib/builder.py", line 227, in build
    gdef = self.buildGDEF()  # build unconditionally so we can warn below
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/feaLib/builder.py", line 763, in buildGDEF
    gdef.MarkGlyphSetsDef = self.buildGDEFMarkGlyphSetsDef_()
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/feaLib/builder.py", line 822, in buildGDEFMarkGlyphSetsDef_
    return otl.buildMarkGlyphSetsDef(sets, self.glyphMap)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/otlLib/builder.py", line 2618, in buildMarkGlyphSetsDef
    self.Coverage = [buildCoverage(m, glyphMap) for m in markSets]
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/otlLib/builder.py", line 2618, in <listcomp>
    self.Coverage = [buildCoverage(m, glyphMap) for m in markSets]
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/otlLib/builder.py", line 58, in buildCoverage
    self.glyphs = sorted(set(glyphs), key=glyphMap.__getitem__)
KeyError: <fontTools.feaLib.ast.GlyphName object at 0x10ea35b10>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/__main__.py", line 620, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 787, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 1051, in run_from_designspace
    self._run_from_designspace_static(
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 1135, in _run_from_designspace_static
    self.run_from_ufos(
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 1217, in run_from_ufos
    self.build_otfs(ufos, cff_version=cff_version, **kwargs)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 247, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 580, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 441, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'sources/shantellsans-wght_ital_IRGL.glyphs' -> 'master_ufo/ShantellSans.designspace' -> 'master_ufo/shantell--light.ufo': Compiling UFO failed: <fontTools.feaLib.ast.GlyphName object at 0x10ea35b10>
```

I’ve tried commenting out all feature code in the problem UFO, but that doesn't seem to correct this.

The build _does_ work with fonttools==4.34.4, but then I get this as a warning:

`WARNING:fontTools.ttLib.tables.otBase:hb.repack failed to serialize 'GPOS', attempting fonttools resolutions ; the error message was: RepackerError`

Is there some way I can determine if an incorrect glyph name is blocking this build? Should I instead be filing this issue with FontTools?

Thank you for any insights!

**Comment by anthrotype** [comment]
the WARNING is just that, a warning (it says harfbuzz failed to re-pack the GPOS table as sometimes happens for very big tables that it doesn't know how to split up yet) so that's not the problem.

the error comes from that `KeyError: <fontTools.feaLib.ast.GlyphName object at 0x10ea35b10>`

somehow an ast.GlyphName object is used instead a glyph name `str` and that blows things up. maybe the ufo2ft cursFeatureWriter or the gdefFeatureWriter are responsible. 

How can I reproduce this?

**Comment by arrowtype** [comment]
@anthrotype Thanks for breaking it down a bit, and guessing what might be the cause!
 
> How can I reproduce this?

If you’re up for it, I’ve made a simplified reproduction repo, which should hopefully make a reproduction as quick and easy as possible. I can’t yet share the font publicly, so I invited you as a collaborator:

https://github.com/arrowtype/fontmake-issue-925-repro/invitations

Please let me know if that works for you!

**Comment by anthrotype** [comment]
can you please retry using fonttools==4.36.0? it contains https://github.com/fonttools/fonttools/pull/2744 which works around this issue

**Comment by vv-monsalve** [comment]
It worked! Thank you, @anthrotype.

**Comment by arrowtype** [comment]
FontTools 4.36.0 seems to work perfectly here! Thanks to you, Just, and Simon for working that out!
