### ISSUE TITLE
Can't generate font >> invalid literal for int() with base 10: 'bit 29'

### ISSUE THREAD

**Issue by etunni** [googlefonts/fontmake#935]
Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'

**Comment by anthrotype** [comment]
can you show the full traceback (run fontmake with --verbose DEBUG option)? It might be a bug or unsupported feature in glyphsLib

**Comment by etunni** [comment]
> can you show the full traceback (run fontmake with --verbose DEBUG option)? It might be a bug or unsupported feature in glyphsLib

I hope this help you

Last login: Fri Sep  9 07:24:51 on console
➜  ~ tipo
(venv) ➜  ~ /Users/etunni/Documents/Meet/Meet\ 2015/Omnibus/chivovf 
(venv) ➜  chivovf ./build.sh                                              
rm: ./Fonts/static/ttf/*.ttf: No such file or directory
rm: ./Fonts/static/otf/*.otf: No such file or directory
rm: ./Fonts/*.ttf: No such file or directory
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Chivo-Italic.glyphs" file into <GSFont>
ERROR:root:In 'Chivo-Italic.glyphs': Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'
Traceback (most recent call last):
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 187, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 4318, in __init__
    p.parse_into_object(self, openstep_plist.load(fp, use_numbers=True))
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 69, in parse_into_object
    return self._parse_dict_into_object(res, value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 89, in _parse_dict_into_object
    getattr(res, f"_parse_{sane_name}_dict")(self, d[name])
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 4248, in _parse_customParameters_dict
    _customParameters = parser._parse(value, GSCustomParameter)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 59, in _parse
    return self._parse_list(d, new_type)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 66, in _parse_list
    return [self._parse(x, new_type) for x in d]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 66, in <listcomp>
    return [self._parse(x, new_type) for x in d]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 61, in _parse
    return self._parse_dict(d, new_type)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 81, in _parse_dict
    self._parse_dict_into_object(res, text)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 98, in _parse_dict_into_object
    res[name] = d[name]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 336, in __setitem__
    setattr(self, key, value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 1366, in setValue
    value = readIntlist(value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 349, in readIntlist
    return _mutate_list(int, src)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 344, in _mutate_list
    l[i] = fn(l[i])
ValueError: invalid literal for int() with base 10: 'bit 29'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 620, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 784, in run_from_glyphs
    ufo_structure=kwargs.get("ufo_structure"),
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 189, in build_master_ufos
    raise FontmakeError("Loading Glyphs file failed", glyphs_path) from e
fontmake.errors.FontmakeError: In 'Chivo-Italic.glyphs': Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'
Processing ./Fonts/static/ttf/*.ttf
Traceback (most recent call last):
  File "/Users/etunni/venv/bin/gftools-fix-hinting.py", line 56, in <module>
    main()
  File "/Users/etunni/venv/bin/gftools-fix-hinting.py", line 43, in main
    font = TTFont(args.font)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 129, in __init__
    file = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './Fonts/static/ttf/*.ttf'
mv: rename ./Fonts/static/ttf/*.ttf.fix to ./Fonts/static/ttf/*.ttf: No such file or directory
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Chivo-Italic.glyphs" file into <GSFont>
ERROR:root:In 'Chivo-Italic.glyphs': Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'
Traceback (most recent call last):
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 187, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 4318, in __init__
    p.parse_into_object(self, openstep_plist.load(fp, use_numbers=True))
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 69, in parse_into_object
    return self._parse_dict_into_object(res, value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 89, in _parse_dict_into_object
    getattr(res, f"_parse_{sane_name}_dict")(self, d[name])
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 4248, in _parse_customParameters_dict
    _customParameters = parser._parse(value, GSCustomParameter)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 59, in _parse
    return self._parse_list(d, new_type)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 66, in _parse_list
    return [self._parse(x, new_type) for x in d]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 66, in <listcomp>
    return [self._parse(x, new_type) for x in d]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 61, in _parse
    return self._parse_dict(d, new_type)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 81, in _parse_dict
    self._parse_dict_into_object(res, text)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 98, in _parse_dict_into_object
    res[name] = d[name]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 336, in __setitem__
    setattr(self, key, value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 1366, in setValue
    value = readIntlist(value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 349, in readIntlist
    return _mutate_list(int, src)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 344, in _mutate_list
    l[i] = fn(l[i])
ValueError: invalid literal for int() with base 10: 'bit 29'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 620, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 784, in run_from_glyphs
    ufo_structure=kwargs.get("ufo_structure"),
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 189, in build_master_ufos
    raise FontmakeError("Loading Glyphs file failed", glyphs_path) from e
fontmake.errors.FontmakeError: In 'Chivo-Italic.glyphs': Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'
Processing ./Fonts/static/otf/*.otf
Traceback (most recent call last):
  File "/Users/etunni/venv/bin/gftools-fix-hinting.py", line 56, in <module>
    main()
  File "/Users/etunni/venv/bin/gftools-fix-hinting.py", line 43, in main
    font = TTFont(args.font)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 129, in __init__
    file = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './Fonts/static/otf/*.otf'
mv: rename ./Fonts/static/otf/*.otf.fix to ./Fonts/static/otf/*.otf: No such file or directory
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Chivo-Italic.glyphs" file into <GSFont>
ERROR:root:In 'Chivo-Italic.glyphs': Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'
Traceback (most recent call last):
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 187, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 4318, in __init__
    p.parse_into_object(self, openstep_plist.load(fp, use_numbers=True))
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 69, in parse_into_object
    return self._parse_dict_into_object(res, value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 89, in _parse_dict_into_object
    getattr(res, f"_parse_{sane_name}_dict")(self, d[name])
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 4248, in _parse_customParameters_dict
    _customParameters = parser._parse(value, GSCustomParameter)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 59, in _parse
    return self._parse_list(d, new_type)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 66, in _parse_list
    return [self._parse(x, new_type) for x in d]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 66, in <listcomp>
    return [self._parse(x, new_type) for x in d]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 61, in _parse
    return self._parse_dict(d, new_type)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 81, in _parse_dict
    self._parse_dict_into_object(res, text)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/parser.py", line 98, in _parse_dict_into_object
    res[name] = d[name]
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 336, in __setitem__
    setattr(self, key, value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/classes.py", line 1366, in setValue
    value = readIntlist(value)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 349, in readIntlist
    return _mutate_list(int, src)
  File "/Users/etunni/venv/lib/python3.7/site-packages/glyphsLib/types.py", line 344, in _mutate_list
    l[i] = fn(l[i])
ValueError: invalid literal for int() with base 10: 'bit 29'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/__main__.py", line 620, in main
    project.run_from_glyphs(inputs.glyphs_path, **args)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 784, in run_from_glyphs
    ufo_structure=kwargs.get("ufo_structure"),
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/etunni/venv/lib/python3.7/site-packages/fontmake/font_project.py", line 189, in build_master_ufos
    raise FontmakeError("Loading Glyphs file failed", glyphs_path) from e
fontmake.errors.FontmakeError: In 'Chivo-Italic.glyphs': Loading Glyphs file failed: invalid literal for int() with base 10: 'bit 29'
(venv) ➜  chivovf
