### ISSUE TITLE
Generating fonts from Designspace failed: unsigned short is greater than maximum [error when generating variable font]

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontmake#939]
```
INFO:fontTools.varLib:Merging TT hinting
DEBUG:fontTools.ttLib.ttFont:Compiling 'glyf' table
DEBUG:fontTools.ttLib.ttFont:Writing 'glyf' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'maxp' table
DEBUG:fontTools.ttLib.ttFont:Writing 'maxp' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'loca' table
DEBUG:fontTools.ttLib.ttFont:Writing 'loca' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'head' table
DEBUG:fontTools.ttLib.ttFont:Writing 'head' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'hmtx' table
DEBUG:fontTools.ttLib.ttFont:Writing 'hmtx' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'hhea' table
DEBUG:fontTools.ttLib.ttFont:Writing 'hhea' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'OS/2' table
DEBUG:fontTools.ttLib.ttFont:Writing 'OS/2' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'cmap' table
DEBUG:fontTools.ttLib.ttFont:Writing 'cmap' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'name' table
DEBUG:fontTools.ttLib.ttFont:Writing 'name' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'post' table
ERROR:root:In 'SHSans-VF-ufo-test.designspace': Generating fonts from Designspace failed: unsigned short is greater than maximum
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontmake\font_project.py", line 1003, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontmake\font_project.py", line 1086, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontmake\font_project.py", line 342, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ufo2ft\__init__.py", line 570, in compileVariableTTF
    return call_postprocessor(varfont, baseUfo, glyphSet=None, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ufo2ft\__init__.py", line 74, in call_postprocessor
    postProcessor = postProcessorClass(otf, ufo, glyphSet=glyphSet)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ufo2ft\postProcessor.py", line 50, in __init__
    self.otf = _reloadFont(otf)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ufo2ft\postProcessor.py", line 394, in _reloadFont
    font.save(stream)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 184, in save
    writer_reordersTables = self._save(tmp)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 224, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 647, in _writeTable
    tabledata = self.getTableData(tag)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 51, in compile
    data = data + self.encode_format_2_0(ttFont)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 174, in encode_format_2_0
    indices.append(index)
OverflowError: unsigned short is greater than maximum

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontmake\__main__.py", line 602, in main
    project.run_from_designspace(inputs.designspace_path, **args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontmake\font_project.py", line 1017, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'SHSans-VF-ufo-test.designspace': Generating fonts from Designspace failed: unsigned short is greater than maximum
```

How should I begin with debugging the issue? The above comes from generating fonts from two UFOs and a DesignSpace file.

**Comment by anthrotype** [comment]
how many glyphs are in the font? I suspect a lot...

**Comment by anthrotype** [comment]
post table format 2.0 fails to compile because there are more glyphs than an unsigned integer can fit. I think I saw a similar issue somewhere.. maybe @punchcutter knows

**Comment by NightFurySL2001** [comment]
65535; came from Source Han Sans. https://github.com/adobe-fonts/source-han-sans @punchcutter is the maintainer for Source Han, so he definitely will know something about this......

I converted the font using this script here: https://github.com/NightFurySL2001/py-fonttools-script/blob/main/convert_ufo.py , using the masters CID-keyed CFF OTF generated from source file.

**Comment by NightFurySL2001** [comment]
Directly rebuilding the master UFO font back to OTF failed too (which i am suspecting the same problem):
```
INFO:fontmake.font_project:Building OTF for SourceHanSansSCVF-Regular
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters.base:Running DecomposeComponentsFilter on SourceHanSansSCVF-ExtraLight
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.outlineCompiler:The trademark was normalized for storage in the CFF table and consequently some characters were dropped: 'Source is a trademark of Adobe in the United States andor other countries.'
INFO:ufo2ft.outlineCompiler:The copyright was normalized for storage in the CFF table and consequently some characters were dropped: 'Copyright 2014-2021 Adobe http:www.adobe.com, with Reserved Font Name 'Source'.'
fontmake: Error: In 'SourceHanSansSCVF-ExtraLight.ufo': Compiling UFO failed: 'H' format requires 0 <= number <= 65535
```

**Comment by punchcutter** [comment]
I wrote more about this in https://github.com/adobe-fonts/source-han-sans/issues/297#issuecomment-975175400 
We have to override some things to build Source Han/Noto CJK variable fonts. We can get away with it easily now because we don't need glyph names for any designspace subs or anything (see https://github.com/googlefonts/ufo2ft/issues/462#issuecomment-779809955).

**Comment by NightFurySL2001** [comment]
Using that code still produce the same error:
```
hb.repack failed to serialize 'GSUB', reverting to pure-python serializer; the error message was: RepackerError
Traceback (most recent call last):
  File "D:\Desktop\font-project\make-font\shs-vf\vf\try-build\build_ttf_vf.py", line 62, in <module>
    build("SHSans-VF-ufo-test.designspace", "SHSans-VF-test-[wght].ttf", "tables")
  File "D:\Desktop\font-project\make-font\shs-vf\vf\try-build\build_ttf_vf.py", line 58, in build
    font.save(dest)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 184, in save
    writer_reordersTables = self._save(tmp)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 224, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 647, in _writeTable
    tabledata = self.getTableData(tag)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 51, in compile
    data = data + self.encode_format_2_0(ttFont)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 174, in encode_format_2_0
    indices.append(index)
OverflowError: unsigned short is greater than maximum
```

**Comment by punchcutter** [comment]
Well that's how Source Han is built so you must have something different in the setup. Are you using fontmake? For the code I posted we don't use fontmake at all. That calls ufo2ft directly so bypasses a lot of other unneeded stuff. For the TTF of Source Han we really only need the outlines in this step and most of the other tables are copied from the OTF.

**Comment by anthrotype** [comment]
@NightFurySL2001 @punchcutter could you please try to build using ufo2ft from `no-reload-font` branch of this PR https://github.com/googlefonts/ufo2ft/pull/671 and see if that fixes the issue of overflowing post format 2? 

I suspect we also need to prevent ufo2ft from adding a .notdef glyph when there's already cid00000, but that should be easy to do.

**Comment by NightFurySL2001** [comment]
@anthrotype I tried the `no-reload-font` branch and the problem still persists. Just in case, I used the following commands for reference:
```
git clone https://github.com/googlefonts/ufo2ft.git
cd .\ufo2ft\
git checkout no-reload-font
pip3 uninstall ufo2ft
pip3 install -e .
>>> Successfully installed ufo2ft-2.29.0b2.dev237+gf79b160
```

Building with Python script but modified the override method:
```py
class CJKOutlineTTFCompiler(ufo2ft.outlineCompiler.OutlineTTFCompiler):

    @staticmethod
    def makeMissingRequiredGlyphs(font, glyphSet, sfntVersion, notdefGlyph=None):
        print(".notdef skipped")
        # Make sure we don't add .notdef
        return
```
result in the following output:
```
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
.notdef skipped
.notdef skipped
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Cannot look up family name, assign the 'familyname' attribute to the default source.
Traceback (most recent call last):
  File "D:\Desktop\font-project\make-font\shs-vf\vf\try-build\build_ttf_vf.py", line 63, in <module>
    build("SHSans-VF-ufo-test.designspace", "SHSans-VF-test-[wght].ttf", "tables")
  File "D:\Desktop\font-project\make-font\shs-vf\vf\try-build\build_ttf_vf.py", line 59, in build
    font.save(dest)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 185, in save
    writer_reordersTables = self._save(tmp)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 225, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 680, in getTableData
    return self.tables[tag].compile(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 51, in compile
    data = data + self.encode_format_2_0(ttFont)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 174, in encode_format_2_0
    indices.append(index)
OverflowError: unsigned short is greater than maximum
```

But yeah, this problem is out of scope of `fontmake` and a problem in `fontTools`/`ufo2ft` now.

**Comment by anthrotype** [comment]
where can I find the UFOs and designspace so I can try to reproduce this?

**Comment by anthrotype** [comment]
can you try to set this lib key "com.github.googlei18n.ufo2ft.keepGlyphNames" to False in all the master UFOs before calling compileVariableTTF? That will make the ufo2ft.postProcessor set the post to format 3.0 on the built VF which is what you want:

https://github.com/googlefonts/ufo2ft/blob/71ef6caa1f1fc63b487e9d92bd5735b5d117f506/Lib/ufo2ft/postProcessor.py#L67-L74

We should document this better, and maybe expose that as a fontmake option.

**Comment by NightFurySL2001** [comment]
Adding "com.github.googlei18n.ufo2ft.keepGlyphNames" to False in lib.plist successfully exported the TTF variable font through `compileVariableTTF`. Some minor errors popped up (e.g. `Cannot look up family name, assign the 'familyname' attribute to the default source.`, `hb.repack failed to serialize 'GSUB', attempting fonttools resolutions ; the error message was: RepackerError`) and some `vmtx` seems broken, but all looks good and fine so far.

I do agree to add using `post` table version 3 as a fontmake option is a good solution.
