### ISSUE TITLE
Generating fonts from Designspace failed: 'openTypeOS2WeightClass' must be between 1 and 1000

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontmake#956]
I’m running into an error when attempting to generate instance UFOs from a designspace. This is surprising, because the same designspace is building into a variable font without issue, so the sources would seem to be compatible and set up correctly.

Here’s the basic call I’m attempting:

`fontmake -m "familyname.designspace" -o ufo -i`

Possibly related to https://github.com/googlefonts/fontmake/issues/883, in that both issues seem to involve unexpected numbers being set into OS/2.usWeightClass.

When I set Fontmake to `--verbose DEBUG`, here’s what I get:

<details>
<summary><b>Fontmake traceback</b> (Click to expand)</summary>

```
DEBUG:fontmake.font_project:ufoLib UFO validation is disabled
INFO:fontmake.font_project:Interpolating master UFOs from designspace
WARNING:fontmake.instantiator:The source temp_master.0 (familyname-Display_Hairline.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.4 (familyname-Display_Bold.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.6 (familyname-Display_Ultra.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
WARNING:fontmake.instantiator:The source temp_master.10 (sparse--familyname-Text_500.ufo) contains different groups than the default source. The default source's groups will be used for the instances.
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Hairline"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text ExtraThin"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Thin"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text ExtraLight"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Light"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Regular"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Medium"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text SemiBold"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Bold"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text ExtraBold"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Black"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Text Ultra"
INFO:fontmake.font_project:Generating instance UFO for "Familyname Standard Hairline"
ERROR:root:In 'source/familyname-varfontprepped-2022_11_27-22_06/familyname-wght_1_1000-opsz_12_96--w_sparse_supports--statics.designspace': Generating fonts from Designspace failed: 'openTypeOS2WeightClass' must be between 1 and 1000
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 1091, in run_from_designspace
    self._run_from_designspace_static(
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 1155, in _run_from_designspace_static
    ufos.extend(
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 893, in interpolate_instance_ufos
    instance.font = generator.generate_instance(instance)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/instantiator.py", line 347, in generate_instance
    self._generate_instance_info(instance, location_normalized, location, font)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/instantiator.py", line 429, in _generate_instance_info
    info_instance.extractInfo(font.info)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontMath/mathInfo.py", line 237, in extractInfo
    setattr(otherInfoObject, attr, v)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/attr/_make.py", line 1082, in __setattr__
    nval = hook(self, a, val)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/attr/setters.py", line 24, in wrapped_pipe
    rv = setter(instance, attrib, rv)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/attr/setters.py", line 53, in validate
    v(instance, attrib, new_value)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/ufoLib2/objects/info/__init__.py", line 284, in _validate_weight_class
    raise ValueError("'openTypeOS2WeightClass' must be between 1 and 1000")
ValueError: 'openTypeOS2WeightClass' must be between 1 and 1000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/__main__.py", line 675, in main
    project.run_from_designspace(inputs.designspace_path, **args)
  File "/Users/stephennixon/type-repos/familyname/venv/lib/python3.10/site-packages/fontmake/font_project.py", line 1120, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'source/familyname-varfontprepped-2022_11_27-22_06/familyname-wght_1_1000-opsz_12_96--w_sparse_supports--statics.designspace': Generating fonts from Designspace failed: 'openTypeOS2WeightClass' must be between 1 and 1000
```

</details>

If I insert a print statement to see what OS2WeightClass is being generated for Familyname Standard Hairline, I get the result of `0`.  This is strange, because my designspace is set up for weights 1–1000, and I’ve been building from it for months without seeing this issue.

Further project details: 
- The project is weight + opsz
- The project has 6 main sources:
  -  max opsz; weights 1, 700, 1000
  - min opsz; weights 1, 700, 1000
  - There are also some support sources to adjust the interpolation of various glyphs at locations like `min opsz, wght 200`, `min opsz, wght 500`, etc
- The project interpolates into 36 instances
- The instance which fails to generate is at an interpolated opsz, weight 1

Here’s the instance entry:

```xml
<instance familyname="Familyname Standard" stylename="Hairline" filename="instances/Familyname_Standard-Hairline.ufo">
    <location>
      <dimension name="Weight" xvalue="1"/>
      <dimension name="Optical Size" xvalue="54"/>
    </location>
    <kerning/>
    <info/>
  </instance>
```

The weight axis is set up like this:

```xml
    <axis tag="wght" name="Weight" minimum="1" maximum="1000" default="700">
      <labelname xml:lang="en">Weight</labelname>
      <labels>
        <label uservalue="1" name="Hairline" />
        <label uservalue="50" name="ExtraThin" />
        <label uservalue="100" name="Thin" />
        <label uservalue="200" name="ExtraLight" />
        <label uservalue="300" name="Light" />
        <label uservalue="400" name="Regular" linkeduservalue="700" elidable="true" />
        <label uservalue="500" name="Medium" />
        <label uservalue="600" name="SemiBold" />
        <label uservalue="700" name="Bold" linkeduservalue="400"/>
        <label uservalue="800" name="ExtraBold" />
        <label uservalue="900" name="Black" />
        <label uservalue="1000" name="Ultra" />
      </labels>
      <map input="1000" output="1000"/>
      <map input="900" output="856"/>
      <map input="800" output="756"/>
      <map input="700" output="700"/>
      <map input="600" output="600"/>
      <map input="500" output="500"/>
      <map input="400" output="400"/>
      <map input="300" output="300"/>
      <map input="200" output="200"/>
      <map input="100" output="100"/>
      <map input="50" output="50"/>
      <map input="1" output="1"/>
    </axis>
```

I’m unsure of what I might try next. It seems like the value is just getting interpolated or rounded incorrectly, but I’m not sure if I’ve done anything to trigger that. Please let me know if I can answer any questions.

Thanks for taking a look!

**Comment by arrowtype** [comment]
Ah, good question, and helpful additional info!

I had briefly looked at that earlier, but incorrectly assumed that it was ignored in the build process.

It was set in only 3 (of 6) of the main sources, as:

```
    <key>openTypeOS2WeightClass</key>
    <integer>400</integer>
```

With that removed, the UFO instances get generated with `openTypeOS2WeightClass` values exactly as expected.

Thank you for pointing out my obvious (in hindsight) error!
